- README.md
- src/DayPicker.js
Pass the SytheticEvent to the onPrevMonthClick callback and the onNextMonthClick callback so that the developer can access it as needed.
Updated the corresponding documentation in the README.
My editor also automagically cleaned up some whitespace. I can undo that if you'd like.
Fixes #10
> Pass SyntheticEvent to onPrev/NextMonthClick callbacks

- README.md
- example/src/scss/daypicker.scss
- src/DayPicker.js
In reference to https://github.com/gpbl/react-day-picker/issues/11, @iancmyers @gpbl
I separated out the logic to render a single month into its own method, and simply called it as many times as was indicated by the new property. Each month is its own table, and I added some custom styling to the example css to make the months render side-by-side (which I think is desirable). 
Here are some screenshots of the example with multiple months:
It was super awesome how easy it was to add this functionality! :) Let me know what you guys think? This does not affect the default calendar whatsoever. It still functions exactly as it did before.
> Adds 'numberOfMonths' option to the DayPicker, allowing multiple months to be displayed side-by-side.

- src/DayPicker.js
Because React reuses event objects by the time the event reaches the onPrev/NextMonthClick callback all of the attributes are null.
This change has React persist the events so that they can actually be used in the callback.
> Persist events on month changes

- site/src/APIPage.js
- src/DayPicker.js
- tests/DayPicker.js
Adds an optional `onCaptionClick` prop (similar to `onDayClick`) that allows developer to specify a function to be run when the user clicks the caption in the header (month display).
> Feature: onCaptionClick

- src/DayPicker.js
- test/DayPicker.js
Alternative solution to #57, and testing that `componentWillReceiveProps` sets `currentMonth` to the first day of the month
> Fix currentMonth when props are being updated

- src/DayPicker.js
There seem to be no real need to stop event propagation in this case, and doing so might cause unwanted side-effects in certain cases.
> Let the event from next/previous month click to propagate.

- src/DayPicker.js
- src/style.css
This PR address reverts [this commit](https://github.com/gpbl/react-day-picker/commit/0164a38f651771c00d3b4949898937d2013c7ddd) adding a `table-row` element around the `DayPicker-Weekday` table cells. #82
> Restore the row for the weekdays header (fix #82)

- test/DayPicker.js
When require('../src/DayPicker') returns a object. The class itself is on 'default' property.
It's the way ES6 modules work.
> Fix incorrect import

- package.json
Allows the require in css to be
```javascript
import 'react-date-picker';
``` 
instead of
```javascript
import 'react-date-picker/lib/style.css';
```
> Adds the style definition to package.json

- docs/LocaleUtils.md
In the documentation the return type of `getFirstDayOfWeek` is a `bool`. This should actually be a `number`. The [code that uses](https://github.com/gpbl/react-day-picker/blob/master/src/Helpers.js#L37) this value does a strict comparison with a number
```
if(week.length > 0 && day.getDay() === firstDayOfWeek) {
```
Also that value can indeed be a number different than 0 (Sunday) and 1 (Monday), for example in Hebrew it is commonly 6 (Saturday).
> Change documented return type of getFirstDayOfWeek to number

- src/DayPicker.js
- test/DayPicker.js
keyboard nav:
* navigate between weeks with up/down arrow keys when inner grid is focused
* navigate between years with up/down arrow keys when outer div is focused
aria:
* added additional aria labels so screen reader reads date when focus changes (tested on OSX/chrome/voiceover and win8/IE11/JAWS)
There are 5 commits. Started with some refactoring to simplify DayPicker, then added keyboard nav features and aria labels to date cells, so that it works better with screen readers.
Look at each commit independently.
Test keyboard nav in example app.
Test with screen reader in example app (cmd-f5 to enable voiceover in OSX).
> Keyboard nav and aria improvements

- docs/GettingStarted.md
I made a little addition to documentation, about `modifiers` section
In your `selected` function when no day is selected (for example when datepicker is rendered on the page, and the user hasn't chose some date yet) the `selectedDay` is `null`, and this code will throw an error `Uncaught TypeError: Cannot read property 'getDate' of null`.
Users who will copy this chunk of code will get this error, so i added a little check for the preventing of such situation.
> handle the situation when no day is selected

- src/DayPicker.js
This can be helpful if you need to figure out what version of a library is actually running in your app.
The downside is that as a dev, you have to remember to update this for each release, but I think it's worth it!
> Add version number to DayPicker class

- examples/src/Examples.js
- examples/src/examples/BlockedNavigation.js
- examples/webpack.config.js
- src/DayPicker.js
- test/DayPicker.js
This PR fixes an issue reported by @gnrlbzik when setting `canChageMonth` to `false`. It adds a blocked navigation example as well, plus some code review.
> Make sure month navigation is blocked using canChangeMonth

- src/Helpers.js
As discussed in ticket #174 this pull request replaces the for of loop with a a reduce function, as babel compiles it to a Symbol, which has not support in IE.
> IE11 for of loop fix #174

- docs/API.md
- docs/APIProps.md
- src/DayPicker.js
- src/Helpers.js
- src/Month.js
- test/DayPicker.js
If your calendar is in a container with other elements around and you move between months, the container resizes to the number of weeks shown and this can create an annoying effect.
**Added fixedWeeks flag**
With this new flag, the calendar will show always the same number of
weeks. Exactly 6, because is the maximum number of week that a month can
have.
You can see here an example with this flag enabled:
> Added fixedWeeks flag

- src/DayPicker.js
- src/Month.js
- src/Weekdays.js
- test/DayPicker.js
> navbarElement and weekdayElement instead of component

- src/DayPicker.js
- test/DayPicker.js
As discussed in [#196](https://github.com/gpbl/react-day-picker/issues/196#issuecomment-233597654).
> Add support for adjusting the `initialMonth` to the start of a page.

- examples/src/Examples.js
- examples/src/examples/CalendarOverlay.js
The example of calendar overlay.
A calendar shows on input's focus.
The calendar hides on input's blur caused by outer click, pressing tab, etc.
It doesn't hide by clicking on the calendar itself.
> Add calendar overlay example

- src/Month.js
- src/Weekdays.js
- test/DayPicker.js
I noticed today that the `firstDayOfWeek` locale setting isn’t respected by the weekday headings. 
This change passes through that prop to the `<Weekdays>` component and then appropriately normalises it to a `0-6` integer using the modulo operator so that they do match up to the dates below.
> Ensure weekday labels respect the locale’s `firstDayOfWeek`

- README.md
- docs/API.md
- docs/APIProps.md
- docs/Basic.md
- docs/Modifiers.md
- examples/.eslintrc
- examples/src/Examples.js
- examples/src/examples/AdvancedModifiers.js
- examples/src/examples/DisabledDays.js
- examples/src/examples/InputField.js
- examples/src/examples/Modifiers.js
- examples/src/examples/MultipleDays.js
- examples/src/examples/Range.js
- examples/src/examples/RangeAdvanced.js
- examples/src/examples/Restricted.js
- examples/src/examples/SelectableDay.js
- examples/src/styles/odd-even.css
- examples/src/styles/range.css
- examples/webpack.config.js
- src/DayPicker.js
- src/Helpers.js
- src/PropTypes.js
- test/Helpers.js
This PR extends the type of modifiers values. In addition to a function `(day: Date) => Bool`, modifiers can be now contain:
- `Date` objects
- range objects (e.g. `{ from: new Date(2017, 10, 18), to: new Date(2017, 10, 25) }`)
- after/before objects (e.g. `{ before: new Date() }` or `{ after: new Date(2017, 10, 25) }`
- an array of the above.
Using these new values, we can avoid to create new functions at each rendering (see https://github.com/gpbl/react-day-picker/issues/181) and pre-populate the modifiers with a predefined set of data (see https://github.com/gpbl/react-day-picker/issues/247).
> Accept different kind of modifiers

- docs/API.md
- docs/APIProps.md
- src/DayPicker.js
- src/Helpers.js
- test/DayPicker.js
- test/Helpers.js
This new prop remove the previous behavior of props being spread to the container's `<div />` element by default. Instead, developers should use `containerProps`:
```diff
<DayPicker 
-    data-my-thing="foo" 
+    containerProps={ 'data-my-thing': 'foo' }
/>
```
This will avoid to loop over the prop types to remove the invalid ones, [improving rendering performance](https://github.com/gpbl/react-day-picker/issues/192) as suggested [here](https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b).
> New containerProps prop

- examples/src/Examples.js
- examples/src/examples/AdvancedModifiers.js
- examples/src/examples/CSSModules.js
- examples/src/examples/DisabledDays.js
- examples/src/styles/cssmodules.css
- examples/webpack.config.dev.js
- examples/webpack.config.js
- src/Caption.js
- src/Day.js
- src/DayPicker.js
- src/Helpers.js
- src/Month.js
- src/Navbar.js
- src/Weekdays.js
- src/classNames.js
- test/daypicker/rendering.js
This PR adds a new `classNames` prop to customize the name of the CSS classes used when rendering the component. 
By specifying the `className` for each element, the original BEM syntax can be skipped. The styles can be imported then with CSS Modules. The expected classnames are specified in the proptypes.
To keep the original BEM syntax, the components adopt [an object](https://github.com/gpbl/react-day-picker/compare/css-modules?expand=1#diff-fcd9c1bdd72f16fc0609bdb823042f37) mapping the previous class names. If the `classNames` object is the same as the default, [it will switch](https://github.com/gpbl/react-day-picker/compare/css-modules?expand=1#diff-fa00567f82a050a0ef4e10d8a54c4900R33) to the original behavior.
> Add classNames prop (close #73)

- CHANGELOG.md
- docs/API.md
- docs/APIProps.md
- examples/src/examples/Localized.js
- examples/src/examples/LocalizedCustom.js
- examples/src/examples/LocalizedMoment.js
- src/DayPicker.js
- src/Navbar.js
- test/Navbar.js
- test/daypicker/rendering.js
Add support for aria-label attributes for the navigation bar (see #258) with the new `labels` prop.
> Aria label buttons (close #258)

- src/DayPicker.js
- test/daypicker/navigation.js
Fixes #268 
**Changes:**
This will remove the assumptions about the CSS classes in the DayPicker.getDayNodes method.  Since users can pass in multiple, space delimited classes, we'll need to be a bit careful about how we build up the query.  Also relevant to note: This is tied really tightly to the implementation details of modifiers (sometimes it's a combination of the day and modifier, sometimes it's not).  Not sure if that's the best way going forward, but I wanted to keep changes tightly scoped for this patch.
Also added some tests for the custom classNames use case.  They're basically copies of existing tests with the selectors changed up to match the custom classNames being passed in.
cc @gpbl
> Fix keyboard navigation with custom classNames

- docs/APIProps.md
- src/DayPicker.js
- src/Month.js
- src/Weekdays.js
- test/daypicker/rendering.js
> Allow passing in custom React.Components for navbarElement, captionElement, weekdayElement

- src/Month.js
- src/Weekday.js
- src/Weekdays.js
Fixes: #277 
Per https://www.w3.org/TR/wai-aria/roles#columnheader, the `columnheader` role should go on the equivalent of a `<th>` element and should be owned by something with the `row` role.  
Also, per https://www.w3.org/TR/wai-aria/roles#rowgroup `rowgroup` elements should be owned by something with a `grid` role, so I moved that up as well.
However, this does pose a bit of an issue for people using the `weekdayElement` prop.  Since you're not outputting the result of that in a wrapping div, people passing in an element on that prop will need to be sure to output that role themselves.
Another possible change is for the library to output the wrapping div with the classname and role.  I think that would be a breaking change (resulting change in HTML would probably throw off some …
> Fix aria roles on weekday and month elements

- src/DayPicker.js
- test/daypicker/modifiers.js
The product I am working on allows users to specify a timezone other than that of their browsers, and in doing so might cause what the day picker component thinks `today` is to be different from what the user expects. This change simply allows me to override the `today` modifier with a custom function that could use other references, such as `moment-timezone` objects.
This was run with `test`, `cover`, and `lint`, but if there are other modifications necessary, please let me know.
Thanks, and I welcome your feedback!
> Allow 'today' modifier to override default

- package.json
- test/addons/MomentLocaleUtils.js
It seems that an update of moment has changed the way Italian dates are formatted. See https://github.com/moment/moment/commit/f2af24d53ec8bb2ad61626509e529d339217ff96#diff-0dbfeab7e62c031ad1b2c328b10e2d89 for details. The previously required version of moment was ^2.17.1, which would result in 2.18.1 being installed on a fresh `npm install`. Under 2.18.1 the old unit tests would fail.
This commit updates the required version of moment, and makes sure the unit tests pass with that version.
> Fix unit tests with moment 2.18.1

- src/Day.js
- src/DayPicker.js
- test/daypicker/modifiers.js
Thanks Giampaolo for making such a great date picker component. 
I also recently ran into the case where I wanted to add inline styles. I found that for all cases I could change the styling by importing the css file like you have in your examples. The one exception was for the day modifiers. 
I wanted to propose this as a solution to the inline styles. You would pass in an object of modifiersStyles and when you go into each day, it would go into the modifiersStyles object to see if there was a corresponding style object and apply it to the day, since you've already done the test for which modifiers should be applied :)
It's working well in my local example when I built it, so feel free to use this for inline styles for days if you find it helpful.
Cheers,
Susie
> Add modifiers-styles

- docs/APIProps.md
> Fix typo in APIProps docs

- examples/src/examples/Restricted.js
- src/Helpers.js
- test/Helpers.js
> Fix function modifiers

- docs/DateUtils.md
- examples/src/examples/RangeAdvanced.js
- src/DateUtils.js
- src/Helpers.js
- test/DateUtils.js
- test/Helpers.js
- types/index.d.ts
This PR adds two new functions to `DateUtils` to detect if a day is after/before another day, taking account different timezones. Fixes #307.
> Add isDayAfter/isDayBefore 

- types/index.d.ts
modifiers are often undefined or not passed in as a component prop.
> ModifierUtils dayMatchesModifier make modifier argument optional

- src/Month.js
Hey all! 👋 
First off - this module is wonderful! 🎉 👍 
Just running some accessibility audits on our app over at Buffer - we're using react-day-picker and we're getting a few errors when testing with axe-core! Nothing major, but the Week `div` should have a `role="row"` instead of `role="gridcell"` as it is a child of a `role="rowgroup"` and has children with `role="gridcell"`
Current role structure:
Month (grid) → Weekdays & Body (rowgroup) → Week (gridcell)→ Day (gridcell)
Proposed role structure:
Month (grid) → Weekdays & Body (rowgroup) → Week (row)→ Day (gridcell)
More on  the rowgroup role in the Web Accessibility Initiative – Accessible Rich Internet Applications standards: https://www.w3.org/TR/wai-aria/roles#rowgroup
Let me know if you have any questions! 😸 thanks again!
> change week aria role to row

- src/DayPickerInput.js
Basically, in `DayPickerInput`, updating the `dayPickerProps.month` after it mounts generally does not actually update the month. See #380 for more info.
Caused by a bug in the logic, the fix is pretty self-explanatory.
> Fixes #380 logic bug for checking whether to update `month` state

- docs/Modifiers.md
- src/ModifiersUtils.js
- test/ModifierUtils.js
- types/index.d.ts
> After before modifier

- src/Day.js
- src/Month.js
- test/daypicker/rendering.js
Fixes #400
**Bug:**
To properly control tab behavior, only one of the days should have a tabIndex > -1.  However, when a user first tabs to a calendar with `enableOtherDays` set, focus initially lands on the first day in another month.
**Root Cause:**
Since the Month component only explicitly sets a tabIndex for days in the current month and the Day component defaults the tabIndex to 0, days in other months can be tabbed to.
**Changes:**
- Always pass a tabIndex to the Day component.  Default it to -1.
- Remove the `tabIndex|| 0` when outputting the day, and add a defaultProp which sets the tabIndex to -1.
- Add a test.
cc: @gpbl
> Accessibility: Days should have a negative tabIndex by default

- package.json
- src/Day.js
- src/DayPicker.js
- src/Helpers.js
**Bug:**
Fixes #403 
As mentioned in the issue, this library breaks in IE11 due to missing polyfills.  You could just document the polyfill requirements for this library, but since IE 11 is still [over 2% of browser usage](http://caniuse.com/usage-table) and this is a library, it'd be a good idea to remove code that's incompatible with IE11.
Unfortunately, some babel plugins also add code that's incompatible by default.  The main culprit here is the use of the spread operator to clone a NodeList to an array.  Babel uses a helper for the spread operator, and that helper uses `Array.from`.  Therefore, using the spread operator to clone an array isn't something that can be done here any more.
**Notes:**
[Babel documentation](http://babeljs.io/docs/plugins/transform-runtime/) on the plugins …
> Update code to ensure IE11 compatibility

- src/DayPickerInput.js
- test/daypickerinput/events.js
> Add clickUnselectDay prop

- examples/src/examples/RangeAdvanced.js
A small "fix", which I think makes the range example a bit more usable and intuitive:
- Single-day ranges can be selected
- Any click within the current range will reset the range
- Any click outside the current range will still start a new range
> Single day range + better reset behaviour

- src/DayPicker.js
> Add missing className to wrapper

- docs/docs/api-daypicker.md
- src/Day.js
- src/DayPicker.js
- src/Month.js
- test/daypicker/events.js
- types/index.d.ts
This PR adds the ability to add handlers for mouseUp and mouseDown events on days. This allows one to select dates by moving the mouse over the days while holding down the mouse button.
> Add support for handling mouse up and down on days

- src/Navbar.js
- test/Navbar.js
The RTL support in Navbar lacks symmetry when dealing with disabled interaction with the previous and next buttons.
The fix swaps the values of the showPreviousButton and showNextButton props on RTL.
> Navbar - fix for disabled interaction in RTL

- src/DayPickerInput.js
Hello!
I filed this issue: https://github.com/gpbl/react-day-picker/issues/494.
I have tested this with dayPickerProps and without dayPickerProps.
> DayPickerInput check for prop change with previous props rather than previous state

- package.json
I didn't see an open issue/PR regarding React 16. All the tests passed and I didn't see any errors when using react-day-picker with React 16 in my app.
> Add React 16 as peer dependency

- css/prism.css
This fix makes the text selection visible in Firefox when selecting code inside website snippets.
Right now it is invisible because no background colour is specified for `-moz-selection`. I don't know why it is missing, in Prism.js source it is **[clearly there](https://github.com/PrismJS/prism/blob/22cb0187331d9e7239b23431178981bdcc8e1064/themes/prism.css#L30)**.
> Fixed invisible text selection in website code snippets in Firefox

- src/DayPicker.js
- src/Month.js
I needed a way to render a custom element for week boxes on the left.
Following the `renderDay` implementation I created a `renderWeek` prop.
It defaults to the current behavior, rendering the weekNumber.
> Added `renderWeek` prop to render a custom element for week box

- lib/style.css
The today button isn't showing up for me and I was able to track the problem down to said line in the stylesheet. 
On another page: It would be useful to be able to switch between the today button behaving like a footer and a (working) caption.
> Updated display style property for .DayPicker-Footer

- src/DayPickerInput.js
1. Open Firefox (its not an issue in chrome) https://codesandbox.io/s/XDAE3x0W8
2. Click on day picker input (it shows calendar)
3. Click on navigation bar element (next, prev or nav title elements)
4. Main day picker input loses own focus and calendar stays open
5. Now when you click anywhere outside of calendar. Calendar is still open but is should close.
Looks like the problem in FF is just timing of `this.input.focus(); ` call. This fix is solving the issue.
> Fixed lost input focus

- types/DayPicker.d.ts
According to this issue https://github.com/gpbl/react-day-picker/issues/524, adding the DayModifiers and Modifiers back to type file.
> Add modifiers back to type

- types/index.d.ts
This PR fixes typescript default import.
For more details see issue https://github.com/gpbl/react-day-picker/issues/533
regards
Tristan
> (fix typing) typescript default export

- src/DayPickerInput.js
- test/daypickerinput/events.js
- test/daypickerinput/rendering.js
This PR for #521. `dayPickerProps` moved after `selectedDays` so DayPickerInput's `selectedDays` won't be overridden.
> Don't overrides DayPickerInput selectedDays prop

- types/index.d.ts
Reverts gpbl/react-day-picker#539
This is a breaking change for typescript consumers.
> Revert "(fix typing) typescript default export"

- src/Month.js
In addition to the pull request #497 I require an additional parameter to distinguish weeks outside of the current month (enableOutsideDays & fixedWeeks set to true) and handle those weeks differently.
> add month parameter to renderWeek

- src/DayPicker.js
- test/daypicker/navigation.js
This PR for #543. In case when `toMonth` and `numberOfMonth` are passed to `DayPicker` and `toMonth` earlier or equals  `currentMonth` moves `currentMonth` so `toMonth` rendered last.
> Fixed render of months when toMonth and numberOfMonth are passed

- docs/src/code-samples/examples/selected-range-enter.js
Just fixed a minor typo on an example file.
> Fix typo on selected-range-enter.js example file

- src/style.css
* Please explain clearly your changes. If they involve a lot of code, let discuss them first in on our gitter room: 
* 🙏🏽 Please **DO NOT** build files or update the docs in your pull request – as this may cause git conflicts. Thanks!
> Remove duplicated styles

- src/addons/MomentLocaleUtils.js
- test/addons/MomentLocaleUtils.js
This will cause moment to return `undefined` when parsing a date that doesn't match the format.
`parseDate` value will not override the input value if it doesn't match the format provided.
For: #584
> Set moment in strict mode

- src/DayPickerInput.js
- src/keys.js
- test/daypickerinput/events.js
This fixes Issue #587 (that i opened), adds a keydown handler (tab doesn't get detected on keyup)
which sets clickedInside to true. then, onBlur, overlay remains open, which solves the problem.
> Add support for clicking TAB on input focus

- src/DayPickerInput.js
- src/keys.js
- test/daypickerinput/events.js
Reverts gpbl/react-day-picker#588
> Revert "Add support for clicking TAB on input focus"

- src/DayPickerInput.js
- test/daypickerinput/events.js
> Fixed DayPickerInput not calling dayPickerProps.onMonthChange

- docs/src/pages/api/DayPicker.js
- src/DayPicker.js
- test/daypicker/rendering.js
- yarn.lock
fixes #607 , i can revert doc changes if needed
> fix month prop value in navbar component issue#607

- types/index.d.ts
> Export more types from index.d.ts

- src/DayPicker.js
- types/props.d.ts
Some of my users have difficulties to understand the outside click feature.
If only one month is visible it seems to be ok, but if more then one month is rendered they find it confusing.
Thus I would like to disable this feature. 
With new property name I'm unhappy, but can't come up with a more precise phrase.
> Add possibility to disable roll to prev/next month if outside day is clicked

- DayPicker.dist.js
- DayPicker.js
- src/DayPicker.js
- src/index.js
- webpack.config.js
Ref #632 
Currently umd bundle just doesn't work.
- added `Input` component everywhere
- replace `process.env.NODE_ENV` with production to prevent crashing in umd bundle because prop types package does not exists.
- simplified all entry points in favor of src/index.js
I think this can be published as minor.
before
daypicker.js 102.1K
daypicker.min.js 39.27K
after
daypicker.js 95.68K
daypicker.min.js 39.27K
> Replace env with production to fix umd crashing in runtime

- src/DayPicker.js
- test/daypicker/methods.js
> Fix error with focusing outside nodes 

- src/DayPickerInput.js
- test/daypickerinput/events.js
- test/daypickerinput/rendering.js
Hello @gpbl !
First thank you for your time commitment to this project, it is very useful!
This change is a re-ordering of how the current month is calculated from props. I believe it should use the controlled month from `dayPickerProps.month` before it uses the current `value`.
My specific use case is a 4-month calendar using the DayPickerInput date range selection with a from/to input. In my case I want the first month in the 4 month range to show the start of the range but it will default to using the current value. Which on the `to` DayPickerInput will possibly be a different month.
Otherwise I don't think there is a way to use `DayPickerInput` as a controlled component (w/ redux-form for us) and control the month through props.
Let me know if there is anything else I can provide to …
> Use dayPickerProps controlled month before value.

- src/DayPickerInput.js
- test/daypickerinput/events.js
> Call `onDayChange` with `undefined` when day is not valid

- types/props.d.ts
Fixed error TS7006: Parameter 'DayModifiers' implicitly has an 'any' type.
> Fixed 'any' type on onDayChange second argument

- DayPicker.dist.js
- DayPicker.js
- src/DayPicker.js
- src/index.js
- webpack.config.js
Fixed version
Ref #650 #637 #649
> Fix umd build

- src/Caption.js
- src/Day.js
- src/DayPicker.js
- src/DayPickerInput.js
- src/Month.js
- src/Navbar.js
- src/Weekday.js
- src/Weekdays.js
One day react will land esm and all stuff will updated. We can do it now and don't worry later.
> Prefer react namespace over default export

- docs/package.json
- docs/src/code-samples/examples/input-date-fns.js
- docs/src/pages/docs/input.js
- docs/src/pages/examples/input-date-fns.js
- docs/yarn.lock
I added a small example for how to use the new `formatDate` and `parseDate` props with [date-fns](https://date-fns.org/).
I think this might be able to close https://github.com/gpbl/react-day-picker/issues/342.
> Add example using date-fns to format and parse dates

- docs/src/pages/api/DateUtils.js
- src/DateUtils.js
- src/DayPicker.js
- test/DateUtils.js
> Fix for month being reset when `month` prop is the same month

- docs/src/pages/api/DateUtils.js
- src/DateUtils.js
- src/DayPicker.js
- src/DayPickerInput.js
- test/DateUtils.js
> Lifecycle updates for React 17

- src/DayPickerInput.js
- test/daypickerinput/rendering.js
Fixes Day Picker IE 11 issue #668 for me.
Tested on the following browsers:
IE 11.0.56 @ Windows 10
Chrome/Chromium 65.0.3325.181 @ Windows 10, Ubuntu 18.04 LTS
Chrome 65.0.3325.109 @ Android 4.4
Edge 41.16299.248.0 @ Windows 10
Opera 52.0.2871.40 @ Windows 10
Firefox 59.0.2 @ Windows 10, Ubuntu 18.04 LTS
The proposed solution did not work for me. Therefore try to workaround this issue for IE by using setTimeout.
> Fix day picker for IE 11 (Also see Issue #668)

- docs/src/code-samples/examples/input-custom-overlay.js
- src/DayPickerInput.js
- src/Helpers.js
- test/daypickerinput/events.js
- test/daypickerinput/rendering.js
This undo #700 and #691 as the changes weren’t working as expected. Should also fix #712 and #706
> Fix browser issues with blur/focus by adding timeouts

- docs/src/code-samples/examples/selected-week.js
- docs/src/containers/ExamplePage.js
- docs/src/pages/examples/selected-week.js
I finally had the time to extract https://github.com/gpbl/react-day-picker/issues/686 into the example section.
The implementation slightly differs from the codebox example I previously build.
> Add example for selecting an entire week

- src/style.css
Fix for #610, #725 — previously mouse cursor could flicker because of changing `border-radius` property on hover.
> Update default css styles to avoid flickering

- src/DayPickerInput.js
See https://github.com/gpbl/react-day-picker/issues/746#issuecomment-403203664. This closes #742.
> Do not call `input.focus` if not defined

- src/DayPickerInput.js
I added an extra check on the handleDayClick so it also checks the classNames next to the modifiers.
Closes #689
> Fix disabledDays not working using classNames

- types/common.d.ts
Examples like: https://react-day-picker.js.org/examples/selected-range-enter/ show that modifiers are in fact supported as undefined or nullable. They do not work in typescript without some fair amount of work to ensure the value isn't null, when in fact the library does handle those types.
> Add undefined and null as allowed modifier types

- types/DayPicker.d.ts
The `dayPicker` property was specified incorrectly as a static property
on the `DayPicker` class when it actually exists for the component instance.
> Fix TypeScript type for DayPicker.dayPicker

- DayPickerInput.d.ts
This allows importing from `'react-day-picker/DayPickerInput'` from TypeScript.
Fixes https://github.com/gpbl/react-day-picker/issues/586
I chose to keep the existing type definitions for `DayPickerInput` in the `types` folder and only reference them from the new top-level definition file. Alternatively, the existing definition file could be moved up to the top level as well, but this would be a breaking change for TypeScript consumers.
The new file also takes care of exporting the `DayPickerInput` correctly as default export (see https://github.com/gpbl/react-day-picker/issues/586#issuecomment-372713868)
> Add top-level type definition for DayPickerInput

- src/style.css
Problem: I think the component-styling looks great. But if I need to place it smaller or bigger in my design I have to change all the default stylings.
Suggested solution: if the styling is on the root-level set by `rem` (line: 5) and in the component by `em` I just need to change `.DayPicker {  font-size: 2rem; }` and the whole calendar will scale in proportion to it.
Compatibility: This change should not break any existing styling. People who did manual styling will not be affected, since they reset the default styling. And people who made no changes will not notice, since it's visually equal to the existing codebase.
Sidenote: on [Line 88](https://github.com/gpbl/react-day-picker/blob/master/src/style.css#L88) there was already a `em` format introduced.
> Change formatting to local em-sizes

- src/DayPickerInput.js
- test/daypickerinput/events.js
> Store the typed value even if an invalid date

- package.json
This PR adds the TypeScript definition file added by #762 to the npm bundle.
Ref #586
> Add DayPickerInput.d.ts to npm bundle

- types/props.d.ts
The second argument of function `renderDay(date, modifiers)` should be of type `DayModifiers` instead of type `Modifiers`.
> [Types] renderDay function, modifiers argument

- types/utils.d.ts
These two functions were added in v7.1.6, but type is missing
> Add isDate and isSameMonth to type definition

- src/DayPicker.js
- test/daypicker/navigation.js
- types/props.d.ts
Fix for #837:
Basically, it used the dir prop to decide how to handle the left and right arrows being pressed, switching what they do in RTL.
I've also added the missing `dir` prop to the `DayPickerProps` interface.
The docs for dir usage are missing right now... it would be good to add them, I'd be happy to do that as part of this PR - although the PR template warns against making any changes to the docs
> Switch what left and right keys do in RTL

- src/DayPicker.js
The Arrow keys are used by the browser to scroll, and `DayPicker` uses them to navigate months and years on the body of the `DayPicker`. Currently these events are not marked as handled so the browser does it's default action - which is scrolling when in a container that scrolls, and they bubble to anyone else listening higher up the tree. I've used the cancel event helper to stop that happening.
Here is a sandbox that highlights the issue https://codesandbox.io/s/1q60jqr9ml
> Mark handled keydown events as handled

- types/props.d.ts
I think the typings for `months`, `weekdaysLong` and `weekdaysShort` are too strict. For instance, I get a type error from the following
```
const months = ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D'];
<DayPicker
months={months}
...
/>
```
because the inferred type of the months variable is `string[]`. Whilst the current typings for `months`, `weekdaysLong` and `weekdaysShort` are strictly true in requiring 12, 7 and 7 entries, typescript has difficulty in inferring those types and this makes them unwieldy to use in practice. I suggest loosening them slightly to be `sting[]`.
> Make months and weekdays types slightly less restrictive

- docs/src/pages/api/DayPicker.js
- types/props.d.ts
Changes:
I think the typings on `captionElement` and `weekdayElement` are wrong, and I think the documentation is wrong too. Looking at the default props that `DayPicker` receives, it's clear that the `months` `weekdaysShort` and `weekdaysLong` are passed through to those elements if they are specified on the `DayPicker`. This makes sense, how else will those elements be localized correctly. Therefore if I provide my own elements for the caption or weekday they'll need those props too.
They actually get them :+1: so the only thing that's missing is to update the types. which I've done
I'd also would've updated the docs, but the template advised against that. I will volunteer to update them though :).
> Add missing props from weekdayElement and caption Element

- types/index.d.ts
At the moment it's not possible to import `LocaleUtils`, `DateUtils`, `ModifiersUtils` in Typescript projects, because the utils export is missing in the definition file.
Fixes #812;
> Add missing utils export in TS definitions

- types/common.d.ts
Added 3 missing entries from 
```
https://github.com/gpbl/react-day-picker/blob/master/src/classNames.js
```
to the definition.
> Added missing default entries to ClassNames

- src/DayPickerInput.js
- test/daypickerinput/events.js
- types/props.d.ts
👋 Hello.
While working with `react-day-picker`, I ran into a situation where I wanted to know whether the day picker was open. To help with figuring that out, this PR exposes an `onDayPickerShow` callback to complement the `onDayPickerHide` callback that already exists.
Typically I'd instead opt for keeping the `showOverlay` state local to my own component and use this as a controlled component, but it doesn't look like that is possible (if we'd rather have the ability to do that, I'm willing to open a PR or modify this one to support that instead, but I think we'd still need this callback to know when to set that state to `true`)
> Adds onDayPickerShow to complement onDayPickerHide

- types/utils.d.ts
Every `locale` has `en` as the default value so they're optional. Source: https://github.com/gpbl/react-day-picker/blob/master/src/addons/MomentLocaleUtils.js#L5
> Fix wrong type definition on LocaleUtils

- src/Month.js
If `showWeekNumbers` prop is specified, while `onWeekClick` is not defined, this means that the week numbers are only supposed to be rendered for their visual purpose, not to be interacted with. It seems like tabIndex is left at 0 regardless, which means you have to tab through them even though they cannot be interacted with.
This PR sets tabIndex to -1 on the week numbers if `onWeekClick` is not defined, so that the visually impaired won't have to cycle through the non-interactive elements.
Tests, coverage and linting has run successfully.
> a11y: Set week number tabIndex to -1 if onWeekClick is not defined

- types/DayPickerInput.d.ts
- types/common.d.ts
- types/props.d.ts
This pull request fixes the `classNames` property for the `DayPickerInput` component.
Discussed in #759.
> Fix DayPickerInput classNames TS definitions

- src/DayPickerInput.js
I found it would be useful to have `style` prop passed down to container div of `DayPickerInput`. Sometimes it's much more handy to just apply some small inline styles instead of creating or modifying css classes.
```javascript
// for example if you want to make only this one specific `DatePickerInput` fluid
<DayPickerInput style={{ width: '100%' }} />
```
> Add style prop to DayPickerInput

- types/props.d.ts
It looks like this is [included in the propTypes](https://github.com/gpbl/react-day-picker/blob/421af9f56b1b07ed58f864678b3bbb8617cdaff7/src/DayPicker.js#L92) for the component, but didn't get added to the typescript typings.
> Add tabIndex to DayPickerProps

- types/index.d.ts
Issues: https://github.com/gpbl/react-day-picker/issues/865, https://github.com/gpbl/react-day-picker/issues/887, https://github.com/gpbl/react-day-picker/pull/896
Explicitly list module declaration for exported util functions
* Please explain clearly your changes. If they involve a lot of code, let discuss them first in on our gitter room: 
* 🙏🏽 Please **DO NOT** build files or update the docs in your pull request – as this may cause git conflicts. Thanks!
> fix(types): update type export to allow importing DateUtils methods

- types/DayPicker.d.ts
- types/moment.d.ts
- types/props.d.ts
- types/utils.d.ts
- Fixes the error:
> DateUtils only refers to a type but is being used as a value here TS2693
- I believe this would be a better fix than using namespaces as in #896 due to reasons listed on [this issue](https://github.com/babel/babel/issues/8244#issuecomment-401616905).
resolves #887 & resolves #865
> Fix utils TypeScript types

- src/DayPickerInput.js
- test/daypickerinput/events.js
- test/daypickerinput/methods.js
This is a fix for #875
it sets the time to 12:00:00 after parsing manual input
> Fix different time when date is typed in the input field

- src/DayPickerInput.js
`overlayHasFocus` wasn't being set to false when the overlay was hidden after clicking on a day. 
This was causing the issue seen in: 
Fixes https://github.com/gpbl/react-day-picker/issues/723
> Set overlayHasFocus to false in hideAfterDayClick

- src/DayPickerInput.js
- test/daypickerinput/rendering.js
on DayPickerInput:
when the "dayPickerProps.locale" or "format" props change
the value of the input should be recomputed
Fixes #938
> Fix DayPickerInput value does not recompute on locale change

- package.json
- types/DayPicker.d.ts
- types/DayPickerInput.d.ts
- types/README.md
- types/common.d.ts
- types/index.d.ts
- types/moment.d.ts
- types/props.d.ts
- types/tsconfig.json
- types/utils.d.ts
- yarn.lock
- Upgrade TypeScript version to 3.1 (this version has been around for quite a while, it's safe to assume your users are on TS 3.1+ at this point, and 3.1 has a lot of bug fixes compared to 3.0)
- also remove the explicit dependency on typescript, since dtslint pulls it in and you never invoke it directly
- Enable `noImplicitAny` in tsconfig.json so that you can check you are using types like `React.Component` correctly
- install `@types/react` to get this to work
- Remove redundant re-exports in `types/index.d.ts`
- Since `DateUtils`, `LocaleUtils`, and `ModifiersUtils` are all already `const` values in `utils.d.ts` which are reexported by `export * from './utils';`, there is no need to explicitly export them
- Add a README to the types folder to discourage TypeScript users from importing …
> Improve typings, use TypeScript 3.1

- types/props.d.ts
* Please explain clearly your changes.
the `format` prop in the `DayPickerInput` component is not required as far as i can tell in my project. this just updates the types to match
> Make `format` optional in DayPickerInput

- lib/style.css
The days in the calendar shouldn't wrap when they're in a small container.
This is what it looks like currently:
With the fix:
> Fix text wrapping on DayPicker-Day

- src/DayPickerInput.js
- test/daypickerinput/events.js
Reported as an issue with explanation here: https://github.com/gpbl/react-day-picker/issues/815
Essentially, my issue is that when DayPickerInput is controlled (i.e. takes a 'value' prop) and an invalid date is entered into the input box, an update to the value prop does not clear/update the text within the input (even though the overlay correctly updates the state)
The main issue in this case happens here: https://github.com/gpbl/react-day-picker/blob/master/src/DayPickerInput.js#L576
In this case, this.state.typedValue is defined and remains inside the input, even though this.state.value is the correct state of the input. 
The other changes address warnings that are shown in the console as a result. This message happens when you initialize a controlled input with an undefined value: …
> When DayPicker input state is controlled, correctly set the input text on 'value' prop updates

- src/DayPicker.js
Original Issue: https://github.com/gpbl/react-day-picker/issues/861
Original PR: https://github.com/gpbl/react-day-picker/pull/874
I originally submitted a PR to fix this bug last year, however I mistakenly edited the wrong source files (`/lib/src`) instead of (`/src`).  Consequently this bug fix never made it into v7.4.  This PR makes the same bug fix, but in the correct file.
> Remove initialMonth from defaultProps (#2)

- src/Month.js
When checking if an item is selected or disabled, we need to use the classNames given to the component rather than hardcoded strings. When using hardcoded strings, it will break when custom classNames are provided
> aria-disabled and aria-selected break when using custom classNames prop

- types/props.d.ts
If the `renderDay` and `renderWeek` props are not specified for `<DayPicker>`, defaults [kick in via `defaultProps`](https://github.com/gpbl/react-day-picker/blob/v7/src/DayPicker.js#L150-L151).
This PR indicates to TypeScript that they aren't mandatory.
> DayPicker props renderDay and renderWeek are optional

- types/moment.d.ts
We need to import `MomentLocaleUtils` from `react-day-picker/moment` as a value, not just as a type:
```typescript
import * as React from 'react';
import DayPicker, { DayPickerProps } from 'react-day-picker';
import MomentLocaleUtils from 'react-day-picker/moment';
/* ... */
<DayPicker
// ...
localeUtils={MomentLocaleUtils}
// ...
/>
```
The proposed change fixes this type error.
> Export MomentLocaleUtils as value

- src/addons/MomentLocaleUtils.js
Minor tidy-up to use `moment`'s documented `localeData` APIs, and avoid its private `_locale` field.
> Use moment localeData via documented API

- src/Caption.js
Hiya! Friend from Shedd here again - it turns out the other issue was actually fixed in a later version of v7 (and we just needed to update), so here's a PR just for the `aria-live="polite"` bit!  This allows the NVDA screenreader to announce the changing text in the month header. Thank you for your work! 💖
> Add aria-polite to announce month change during navigation

- types/Modifiers.d.ts
Came across a typing issue when using react-day-picker in our Typescript project.
Specifically, making use of the util function `addDayToRange`. The typing for `addDayToRange` is defined as:
`addDayToRange(day: Date, range: RangeModifier): RangeModifier;`. 
where `export interface RangeModifier {
from: Date;
to: Date;
}`
However the function `addDayToRange`, implemented in `DateUtils.js`expects (and handles) null date objects (from and to) objects, which contradicts the current typing for `RangeModifier`
I simply changed the typing to allow for the dates to be `undefined` within the `RangeModifier` object, and this solved the typing issues we were experiencing.
I also noticed `RangeModifier` was defined twice, so I removed the duplicate.
Cheers!
> Corrected typing for RangerModifier

- docs/src/pages/docs/styling.js
* Please explain clearly your changes. If they involve a lot of code, let discuss them first in on our chat: https://spectrum.chat/react-day-picker?tab=chat
* 🙏🏽 Please **DO NOT** build files or update the docs in your pull request – as this may cause git conflicts. Thanks!
Reading the docs for v7, this link results in a 404 because it doesn't exist on the master branch.
> docs: fix v7 github link in styling doc

- types/DateUtils.d.ts
It's to fix the typing on DateUtils.addDayToRange which doesn't accept undefined as second argument whereas it is perfectly able to handle it.
> Fix DateUtils.addDayToRange second argument typing

- packages/react-day-picker/package.json
- packages/react-day-picker/src/hooks/useModifiers/useModifiers.test.tsx
- packages/react-day-picker/src/hooks/useModifiers/useModifiers.ts
- packages/react-day-picker/src/test/customRender.tsx
- packages/react-day-picker/src/test/customRenderHook.tsx
- packages/react-day-picker/src/test/index.ts
- packages/react-day-picker/style.css
- website/docs/basics/selecting-days-range-min-max.tsx
- website/docs/basics/selecting-days-range.tsx
- website/docs/basics/styling.mdx
- yarn.lock
Additionally, add a missing focused state for selected days to the default stylesheet and fix the two navigable selecting-days-range doc files to allow for de-selecting a range without creating errors
> Fix range selection selected modifiers

- packages/react-day-picker/.eslintrc
- packages/react-day-picker/package.json
- packages/react-day-picker/src/components/Day/hooks/useDayFocus.ts
- packages/react-day-picker/src/contexts/Navigation/useNavigationState.ts
- yarn.lock
I found a couple issues with the new docusaurus updates:
1. There is a hook in website/src/pages/render.tsx (useLocation) that React wants us to hoist to the top of the `Render` function. It spits out an error in the javascript console
2. The svg path for the previous and next icons has no height and width and does not render inside an iframe in the latest version of chrome (see screenshot)
I think we might be able to use the following plugin to catch the first issue. It certainly caught a few issues in the react-day-picker package, which I've fixed below.
I have no idea how to fix the second issue. It works fine in firefox
> (package) Add eslint-plugin-react-hooks

- packages/react-day-picker/src/components/Root/Root.tsx
- packages/react-day-picker/src/contexts/DayPicker/defaultClassNames.ts
- packages/react-day-picker/src/types/Styles.ts
Rename the style: `multiple_month` → `multiple_months`
> chore: rename style to multiple_months

- .github/workflows/react-day-picker.yml
- .github/workflows/website.yml
I think all pushes to a pull request branch will trigger via the pull_request event. Let's test and find out.
> chore: don't run workflows twice on pushes to pull request branches

- packages/react-day-picker/src/hooks/useInput/useInput.ts
When using `useInput` hook, the returned function `setSelected` has incorrect type (doesn't allow 'undefined' as a value)
> fix: small type fix on setSelected

- packages/react-day-picker/src/components/Day/hooks/useDayFocus.ts
- packages/react-day-picker/src/components/Root/Root.tsx
- packages/react-day-picker/src/contexts/Focus/FocusContext.tsx
- packages/react-day-picker/src/types/DayPicker.ts
- website/test-integration/examples/keyboard-focus.test.tsx
To support the use case where users will create a 
new DayPicker in a dialog, this property
allows us to put the focus on the target focus day of the day
grid, as defined by the business logic in the FocusProvider.
See https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html
> feat: support for putting initial focus on the day grid

- website/src/theme/CodeBlock/sandbox/index.tsx
The docs currently say the v8 styles should be imported from /dist/style.css but the Code Sandbox examples in the website point to just /style.css and are subsequently all boken.
> fix: codesandbox style import

- packages/react-day-picker/src/components/Month/Month.test.tsx
- packages/react-day-picker/src/components/Month/Month.tsx
Solves #1393 
I think this got accidentally lost when extracting the `Month` component out of `Root`
(see https://github.com/gpbl/react-day-picker/commit/fc9d913678bbdf3a07c170c4a6e37a3ba1686c3b#diff-562116226713def1cf68ac5328a7d4582aa5d3d431dd7ee5d77bd2802dccaedaL21)
> fix: restore custom caption component

- packages/react-day-picker/src/components/Caption/Caption.test.tsx
- packages/react-day-picker/src/components/Caption/Caption.tsx
- packages/react-day-picker/src/components/CaptionDropdowns/CaptionDropdowns.test.tsx
- packages/react-day-picker/src/components/CaptionDropdowns/CaptionDropdowns.tsx
- packages/react-day-picker/src/components/CaptionDropdowns/index.ts
- packages/react-day-picker/src/components/CaptionNavigation/CaptionNavigation.test.tsx
- packages/react-day-picker/src/components/CaptionNavigation/CaptionNavigation.tsx
- packages/react-day-picker/src/components/CaptionNavigation/index.ts
- packages/react-day-picker/src/index.ts
This PR splits the Caption components into two smaller `CaptionNavigation` and `CaptionDropdowns`. The change should make easier to customize the Caption component.
See related discussion: https://github.com/gpbl/react-day-picker/discussions/1425
> chore: split Caption into smaller components

- packages/react-day-picker/src/contexts/DayPicker/utils/parseFromToProps.test.ts
- packages/react-day-picker/src/contexts/DayPicker/utils/parseFromToProps.ts
If `toMonth` prop passed, we should limit date to the end of the month. Otherwise you cant disable dates in the same month as `toMonth` because it limits to the first day of month. Example: https://codesandbox.io/s/react-day-picker-base-forked-3b557v
> fix: toMonth to include the full month

- website/examples/range-min-max.tsx
The current code gives output like this:
> April 25th, 2022–$April 26th, 2022`
I removed the `$` and the `` ` ``
> website: remove extraneous symbols from range-min-max example

- website/docs/basics/modifiers.md
I found a typo while reading the docs.
> fix(docs): typo in property name

- website/docs/basics/localization.md
- website/docs/basics/styling.md
- website/docs/guides/formatters.md
- website/package.json
- website/src/theme/CodeBlock/index.tsx
- yarn.lock
Upgrade the docusaurus dependencies to the latest beta.
> website(chore): Upgrade docusaurus to beta 22

- packages/react-day-picker/src/components/YearsDropdown/YearsDropdown.tsx
I was adding some custom styling to the dropdown version of the caption, and I noticed that it renders two `rdp-dropdown_month` elements instead of one `.rdp-dropdown_month` and one `.rdp-dropdown_year`. For now I'm using an `:nth-child` selector to differentiate, but I wanted to let you know about it too. Thanks for the great library!
- Use `dropdown_year` class instead of `dropdown_month` class for `YearsDropdown`
> fixed: missing `dropdown_year` CSS class in `YearsDropdown`

- packages/react-day-picker/src/hooks/useDayRender/useDayRender.tsx
When selecting a range, the outside days should not be focused. Fixes #1464.
> fix: disable focus on outside days

- packages/react-day-picker/package.json
- packages/react-day-picker/src/components/Month/Month.tsx
- packages/react-day-picker/src/hooks/useId/index.ts
- packages/react-day-picker/src/hooks/useId/useId.ts
- yarn.lock
We use the good [@reach/auto-id](https://www.npmjs.com/package/@reach/auto-id) package for assigning a unique id to the month captions. This package is creating warnings with DayPicker and React 18 (e.g. #1478), and with React 17 (https://github.com/reach/reach-ui/issues/921).
The [source](https://github.com/reach/reach-ui/blob/dev/packages/auto-id/src/index.tsx) of the package includes some clever code to support both React 17 and the native's `useId` from React 18. However, it doesn't play well in the context of a redistributed package like DayPicker.
I copied in `src` the `useId` [source code](https://github.com/reach/reach-ui/blob/dev/packages/auto-id/src/index.tsx). Skipped [the lines of code](https://github.com/reach/reach-ui/blob/main/packages/auto-id/src/index.tsx#L90-L97) that …
> Fix @reach/auto-id issue by removing the dependency

- packages/react-day-picker/src/contexts/Focus/FocusContext.tsx
- website/test-integration/examples/keyboard.test.tsx
I thought I might as well give it a go myself with this issue:
https://github.com/gpbl/react-day-picker/issues/1491
I did this in the blind as I could not trigger a `develop` script in react-day-picker package. Maybe docs need some update?
Forgot to take user prop weekStartsOn into consideration when focusing start or end of week using home and end keys
I used `weekStartsOn` from the dayPicker context and used it as second parameter in date-fns `startOfWeek` and `endOfWeek`
> Fix: home/end buttons behavior with startOfWeek

- packages/react-day-picker/src/hooks/useId/useId.ts
- If some other dependency has a similar implementation of useId that only returns an incremented number, these IDs can conflict.
- Number-only ID-s are hard to read (mostly personal preference)
This will solve a potential conflict where another third-party dependency has a similar implementation of a useId hook. For example, some other dependency might use the one from reach-ui that this implementation is copied from.
Additionally, it makes the HTML in the DOM a bit easier to read, as `react-day-picker-1` is easier to scan for and find.
Adding a prefix of `react-day-picker-` to the autogenerated ID-s will ensure the ID's generated from this hook are unique and will not conflict with other similar implementations.
> Add prefix to auto generated ids

- react-day-picker.code-workspace
- website/package.json
- website/src/components/RenderExample.tsx
- website/src/components/shadow-dom-styles.css
- website/src/custom.css
- website/src/pages/render.tsx
- website/src/theme/CodeBlock/CodeBlock.module.css
- website/src/theme/CodeBlock/index.tsx
- website/src/theme/CodeBlock/sandpack-app/index.html
- website/src/theme/CodeBlock/sandpack-app/index.tsx
- website/src/theme/CodeBlock/sandpack-app/styles.css
- website/tsconfig.json
- yarn.lock
To better develop react-day-picker, I am changing website so that the examples are rendered in a shadow-dom instead of the sandpack app.
> website: improve layout for the examples

- packages/react-day-picker/src/components/CaptionDropdowns/CaptionDropdowns.tsx
- packages/react-day-picker/src/components/CaptionNavigation/CaptionNavigation.tsx
- packages/react-day-picker/src/contexts/Navigation/useNavigation.test.ts
- packages/react-day-picker/src/contexts/Navigation/useNavigationState.test.ts
- packages/react-day-picker/src/contexts/Navigation/useNavigationState.ts
Fixes #1496 
react-day-picker should call `onMonthChange` every time when `goToMonth` is called. However, in `goToDate` in `NavigationContext`, `onMonthChange` is not called and this is the cause of #1496.
https://github.com/gpbl/react-day-picker/blob/fe80fbbb41ab23ccfb76bbd341e765627e91efd1/packages/react-day-picker/src/contexts/Navigation/NavigationContext.tsx#L61-L65
I moved `onMonthChange` call to inside `goToMonth` to make sure `onMonthChange` is called every time when `goToMonth` is called.
> fix: page keys not working when using setMonth

- packages/react-day-picker/src/contexts/DayPicker/DayPickerContext.tsx
- packages/react-day-picker/src/contexts/DayPicker/useDayPicker.test.ts
The `DayPickerContextValue` should contain the `onSelect` event handler. While this was added in the docs, it wasn't actually available.
> fix: add onSelect to the DayPickerContextValue

- packages/react-day-picker/src/components/Root/Root.test.tsx
- packages/react-day-picker/src/components/Root/Root.tsx
- packages/react-day-picker/src/types/DayPickerBase.ts
Recently we moved the CSS variables into the `.rdp` class in #1499, but this made the issue in #1503 to surface.
In the code we are replacing the value of className instead of appending it.
Append the class name instead of replacing it. To replace it, use `classNames.root`.
> fix: rdp class not added to root element when using className 

- packages/react-day-picker/src/contexts/Focus/FocusContext.tsx
- packages/react-day-picker/src/contexts/Focus/utils/getNextFocus.test.tsx
- packages/react-day-picker/src/contexts/Focus/utils/getNextFocus.tsx
When moving with keyboard, hidden or disabled days still get the focus – even if not visible.
The `getNextFocus` we introduced in does not check if the next focused day is disabled/hidden.
Update `getNextFocus` to skip the disabled/hidden days.
> fix: do not focus disabled or hidden days

- packages/react-day-picker/src/hooks/useDayEventHandlers/useDayEventHandlers.test.tsx
- packages/react-day-picker/src/hooks/useDayEventHandlers/useDayEventHandlers.tsx
Fixes #1506. 
The `onDayClick` event handler is called twice when in selection mode.
This line should not be called when in selection mode:
https://github.com/gpbl/react-day-picker/blob/94e32d18d30505d101290c77dc96d8fd25a861b4/packages/react-day-picker/src/hooks/useDayEventHandlers/useDayEventHandlers.tsx#L98
- Move line into an if statement
- Update test
> fix: `onDayClick` called twice in selection mode

- packages/react-day-picker/src/types/DayPickerBase.ts
- packages/react-day-picker/src/types/DayPickerMultiple.ts
- packages/react-day-picker/src/types/DayPickerRange.ts
Not sure if this would fix `exactOptionalPropertyTypes` in #1456.
> changed: accept `undefined` for the selected prop

- packages/react-day-picker/src/hooks/useInput/useInput.ts
`dayPickerProps` returned from `useInput` ignores `fromYear`/`toYear` and `fromMonth`/`toMonth` set on the options.
Only `option.fromDate`/`options.toDate` is included in `dayPickerProps`. This seems like an oversight and either the parsed `fromDate`/`toDate` should be used or all of the original from/to props should be added.
Use the parsed `fromDate`/`toDate` instead of `options.fromDate`/`options.toDate`.
> fix: use parsed fromDate/toDate in useInput

- packages/react-day-picker/src/components/Day/Day.test.tsx
- packages/react-day-picker/src/components/Day/Day.tsx
- packages/react-day-picker/src/components/Dropdown/Dropdown.test.tsx
- packages/react-day-picker/src/components/Dropdown/Dropdown.tsx
- packages/react-day-picker/src/components/MonthsDropdown/MonthsDropdown.test.tsx
- packages/react-day-picker/src/components/MonthsDropdown/MonthsDropdown.tsx
- packages/react-day-picker/src/components/MonthsDropdown/__snapshots__/MonthsDropdown.test.tsx.snap
- packages/react-day-picker/src/components/Navigation/Navigation.test.tsx
- packages/react-day-picker/src/components/Navigation/Navigation.tsx
- packages/react-day-picker/src/components/WeekNumber/WeekNumber.test.tsx
- packages/react-day-picker/src/components/WeekNumber/WeekNumber.tsx
- packages/react-day-picker/src/components/WeekNumber/__snapshots__/WeekNumber.test.tsx.snap
- packages/react-day-picker/src/components/YearsDropdown/YearsDropdown.test.tsx
- packages/react-day-picker/src/components/YearsDropdown/YearsDropdown.tsx
- packages/react-day-picker/src/components/YearsDropdown/__snapshots__/YearsDropdown.test.tsx.snap
Buttons and input fields have no names, which makes difficult to discriminate them when using custom components. This PR add the missing names.
> changed: add names to fields and buttons

- website/docs/basics/keyboard.md
> doc\(keyboardDocumentation): Corrected the typo error in the KeyboardNavigation file

- packages/react-day-picker/src/types/Matchers.ts
Docs regarding `Matchers` have an example for `functionMatcher` which is incorrect.
Prop `day` is passed but is unused.
Replace `new Day()` with `day`.
> fix(docs): incorrect function matcher example

- website/docs/guides/upgrading.md
There is a minor typo on the v7 -> v8 upgrade docs, where "mayor" was used instead of "major". This PR corrects the typo on that documentation page.
Visible in the first paragraph sentence on https://react-day-picker.js.org/guides/upgrading
N/A
Fix typo
> fix(docs): minor typo in upgrading content

- packages/react-day-picker/src/contexts/Modifiers/utils/matcherToArray.test.ts
- packages/react-day-picker/src/contexts/Modifiers/utils/matcherToArray.ts
> fix: matcherToArray should return a copy of the array

- packages/react-day-picker/src/style.css
closes #1591 
Explain the context of this Pull Request: why are you proposing this change? What is the issue? Include links to issues or discussions.
Steps
1.When showOutsideDays feature is enabled, outside days of the months looks no different than the selected month. This can cause some confusion to the user
2. Render DayPicker with showOutsideDays option
Expected behavior
If we add style to differentiate the days for outside month, users can find the difference between the selected month days against the outside days
Current behaviour
After fix 
Solution
Add opacity as 0.5 for rdp-day_outside class
> chore: Adding opacity to differentiate outside days

- packages/react-day-picker/src/hooks/useDayEventHandlers/useDayEventHandlers.test.tsx
- packages/react-day-picker/src/hooks/useDayEventHandlers/useDayEventHandlers.tsx
- packages/react-day-picker/src/types/DayPickerBase.ts
- packages/react-day-picker/src/types/EventHandlers.ts
feat: add support for `onPointerEnter` and `onPointerLeave` event handlers.
React doesn't call the `onMouseEnter` event handler when the user is moving the mouse over a non-disabled element from a disabled element, but it does call the `onPointerEnter` event handler.
https://github.com/gpbl/react-day-picker/issues/1613 explains the original issue with not being able to trigger an action when the user moves the mouse over a date inside the calendar.
Adding the two event handlers doesn't solve the issue with `onMouseEnter`, but given that `onPointerEnter` does trigger correctly in React 17.0.2 and React 18.0.0, it can be used as a workaround.
> feat: add onDayPointerEnter, onDayPointerLeave props

- website/examples/useinput.tsx
This seems like a good idea 😊
Bumped both years + 1, perhaps this should even be set to 2021 - 2025 so this will be relevant for a while.
Explain the context of this Pull Request: why are you proposing this change? What is the issue? Include links to issues or discussions.
Describe in details why the current code is not working as expected, or why you need to improve it.
Explain the reasoning behind the changes implemented in this PR.
> docs: change example to use current year

- packages/react-day-picker/src/style.css
With default CSS and parameters and when using dropdown and buttons caption layout, the calendar width changes when cycling through the different months with default locale
This may be seen as an issue for two reasons:
- This shifts layout when interacting with the calendar. E.g. when clicking multiples times on "go to next month", it can happen that the "go to previous month" button shifts to the right and the next click is on "go to previous month" instead (reproducible in documentation page)
- This makes the calendar less elegant when using the calendar in a dropdown or with a different background than the page 
This can be reproduced on the currently deployed documentation website, in the example using caption layout "dropdown-buttons": …
> feat: add CSS variable for caption font size

- website/docs/basics/selecting-days.md
In the docs, it is said that an "onSelectRange" prop is available for the range mode, however, such prop doesn't exist and instead "onSelect" can be used.
> Update range mode onSelect docs

- packages/react-day-picker/test/utils/focusDaysGrid.ts
- website/test-integration/examples/controlled.test.tsx
- website/test-integration/examples/custom-multiple.test.tsx
- website/test-integration/examples/custom-single.test.tsx
- website/test-integration/examples/date-picker-dialog.test.tsx
- website/test-integration/examples/dropdown-buttons.test.tsx
- website/test-integration/examples/dropdown.test.tsx
- website/test-integration/examples/focus-recursive.test.tsx
- website/test-integration/examples/formatters.test.tsx
- website/test-integration/examples/from-to-month.test.tsx
- website/test-integration/examples/from-to-year.test.tsx
- website/test-integration/examples/keyboard-focus.test.tsx
- website/test-integration/examples/keyboard.test.tsx
- website/test-integration/examples/modifiers-custom.test.tsx
- website/test-integration/examples/modifiers-today.test.tsx
- website/test-integration/examples/multiple-min-max.test.tsx
- website/test-integration/examples/multiple-months-paged.test.tsx
- website/test-integration/examples/multiple-months.test.tsx
- website/test-integration/examples/multiple.test.tsx
- website/test-integration/examples/range-min-max.test.tsx
- website/test-integration/examples/range-shift-key.test.tsx
- website/test-integration/examples/range.test.tsx
- website/test-integration/examples/single-required.test.tsx
- website/test-integration/examples/single.test.tsx
- website/test-integration/examples/start.test.tsx
- website/test-integration/examples/testcase-1567.test.tsx
- website/test-integration/examples/useinput.test.tsx
- website/test-integration/examples/weeknumber.test.tsx
The tests are throwing a lot of warning – I think after the changes to the focus provider., which for some reasons may cause extra rendering (see #1473). We will address that issue in another instance. For now, we want just clean the test logs.
> website(tests): wrap user events with `act`

- website/examples/date-picker-dialog.tsx
- website/examples/input-range.tsx
- website/examples/useinput.tsx
- website/package.json
- website/src/components/RenderExample.module.css
- website/src/components/RenderExample.tsx
- website/src/components/shadow-dom-styles-dark.css
- website/src/components/shadow-dom-styles.css
- website/src/custom.css
- website/src/theme/CodeBlock/sandpack-app/dark.css
- website/src/theme/CodeBlock/sandpack-app/light.css
- yarn.lock
An attempt to fix https://github.com/facebook/docusaurus/issues/6032 by "reverting" the CSS properties set by Docusaurus, and remove the shadow DOM workaround.
> docs: remove shadow-dom from examples

- src/contexts/Modifiers/utils/isDateInRange.ts
- src/contexts/SelectRange/SelectRangeContext.test.ts
- src/contexts/SelectRange/SelectRangeContext.tsx
- src/contexts/SelectRange/utils/addToRange.ts
A user might want to filter all items before a specific date and modify the `selected` state outside `react-day-picker`. 
While this works perfectly when only `from` is set. But when only `to` is set, the calendar doesn't reflect this state.
The next time a user selects a date, the state is affected like when no values were set at all.
Discussion: https://github.com/gpbl/react-day-picker/discussions/1875
`selected` on a range picker accepts a DateRange where `from` is undefined but `to` is a Date. 
Since this works in one direction and the types allow this state, this component should reflect the other direction too.
To prevent current behaviour changes, All of the logic additions only take effect when `to` is set and `from` is not.
From within this component, this is an unreachable …
> fix: range not selected when missing the `from` value

- src/types/Matchers.ts
A small typo I noticed while copying over the code example from [here](https://react-day-picker.js.org/api/types/matcher).
> docs: fix typo in Matcher example

- src/components/Table/Table.tsx
- src/components/Table/__snapshots__/Table.test.tsx.snap
- website/test-integration/examples/__snapshots__/range.test.tsx.snap
The `role="rowgroup"` attribute added to the `<tbody>` element in `Table.tsx` is redundant and it may cause html validators to fail. (e.g. #1903).
https://github.com/gpbl/react-day-picker/blob/6fc2614dbcb7016ad0362385b44ea016039bc080/src/components/Table/Table.tsx#L54
The role attribute can be removed as it [is the implicit ARIA role](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody) for `tbody`.
Remove the role and update the test screenshots.
> fix(a11y): Remove rowgroup role from tbody element

- website/examples/date-picker-dialog.tsx
- website/examples/testcase-1567.tsx
- website/src/pages/render.tsx
- website/src/theme/CodeBlock/index.tsx
- website/test-integration/examples/spanish-week-starts-on.test.tsx
- website/tsconfig.json
> chore(docs): add strict mode to website

- src/components/Root/Root.test.tsx
- src/components/Root/Root.tsx
- src/types/DayPickerBase.ts
Add `nonce`, `lang` or `title` global attributes to the container. 
Fix #1834.
> feat: support for nonce, lang, title global attributes

- package.json
- pnpm-lock.yaml
- src/components/Months/Months.test.tsx
- src/components/Months/Months.tsx
- src/components/Root/Root.test.tsx
- src/types/DayPickerBase.ts
- website/package.json
As developer I might want to wrap `<DayPicker />` and use [children API](https://react.dev/reference/react/Children) to map over months. For instance I would want to extend pagination to behave like carousel - this seems good use case for using `Children.map`. 
To achieve it we need to be able to host collection of  `<Month />` elements. That's why replacing hardcoded months container by public customisable `<Months />` open additional possibility how library can be consumed. 
```
const AnyComponent = ({children}) => {
return <p>Count: {Children.count(children)}</p>
}
---
<AnyComponent>
<DayPicker numberOfMonths={4} />
</AnyComponent/>
--- output
<p>Count: 1</p>
--- with custom Months
const CustomMonths = ({children}) => (<Months><AnyComponent>{children}</AnyComponent></Months>) …
```
> feat: Introduced custom components "Months"

- src/style.css
- website/docs/basics/styling.md
> feat: new `--rdp-selected-color` CSS variable for text of selected days

- src/components/Months/Months.tsx
- src/contexts/Focus/FocusContext.tsx
- src/contexts/Modifiers/ModifiersContext.tsx
- src/contexts/SelectRange/SelectRangeContext.tsx
The newest version of react-day-picker is not compatible with @types/react 17.
In the last version of the library some props were declare with PropsWithChildren. This interface originally in @types/react 17 is:
```
type PropsWithChildren<P> = P & { children?: ReactNode | undefined };
```
but in @types/react version 18 it has changed to
```
type PropsWithChildren<P = unknown> = P & { children?: ReactNode | undefined };
```
Please note the new default of unknown. This mean new typing relies on @types/react@18 doesn't have to provide the typing when using PropsWithChildren, however it is a must with @types/react@17. The usage of PropsWithChildren in react-day-picker without the argument for the generic type make it incompatible with projects using React 17.
When using PropsWithChildren, …
> Fixing incompatible usage of PropsWithChildren so that typing works with React 17

- src/contexts/DayPicker/DayPickerContext.tsx
- src/contexts/DayPicker/formatters/formatDay.ts
- src/contexts/DayPicker/formatters/formatMonthCaption.ts
- src/contexts/DayPicker/formatters/formatWeekdayName.ts
- src/contexts/DayPicker/formatters/formatYearCaption.ts
- src/types/DayPickerBase.ts
- src/types/Formatters.ts
- src/types/Labels.ts
Build is failing locally because `Locale` types have not been imported. 
Added imports from date-fns `Locale` where missing.
> build(types): add missing `Locale` imports

- src/types/EventHandlers.ts
…ponding type declarations.
when using this within a nextjs app the error Type error: Cannot find module 'types/Matchers' or its corresponding type declarations.
Something is causing a conflict with the tsconfig path matching
Include the Matchers similar to Modifiers to prevent reliance on types/
> fix(types): cannot find module types/Matchers

- README.md
In the current documentation site, the header image looks like a component that seems clickable but opens the same site in the new tab when clicked which leads to a confusing user experience.
I have removed the surrounding anchor tag around the picture element. I understand that it made sense to have it in the readme because it was in Github but since the same readme is parsed and used in the landing page I think the other links in the readme should be enough to help a visitor in Github to get to the website.
> fix(docs): remove anchor from the Readme image

- src/types/Matchers.ts
There are only 7 days in a week, so either the actual range is 0-6 or Sunday is both day 0 and 7
Trying this out, I don't believe days higher than 6 do anything. Updating the comment to reflect the valid range.
Update the comment
> docs: fix typo

- website/examples/modifiers-today.tsx
- website/test-integration/examples/modifiers-today.test.tsx
None
"the today's date" is a bit awkward, so update it to just say "today's date".
> docs: adjust example wording: "the today's date"

- src/types/Matchers.ts
Closes #1976 
I would like to improve the website docs as per the contributing guide's website proofreading line. 
It's important that the documentation is consistent and correct, which is why I would like to add these small fixes to the typos
Removed the incorrect `;` from the following lines:  
`const arrayMatcher: Matcher = [new Date(2019, 1, 2);, new Date(2019, 1, 4)];`
`const afterMatcher: DateAfter = { after: new Date(2019, 1, 2); };`
`const beforeMatcher: DateBefore = { before: new Date(2019, 1, 2); };`
`const rangeMatcher: DateRange = {
from: new Date(2019, 1, 2);,
to: new Date(2019, 1, 5)
};`
on the [Type alias: Matcher](https://react-day-picker.js.org/api/types/Matcher) API reference documentation
> docs: matcher api reference page uses incorrect object syntax

- src/components/Table/utils/daysToMonthWeeks.ts
- src/components/Table/utils/getMonthWeeks.test.ts
- src/components/Table/utils/getMonthWeeks.ts
- src/types/DayPickerBase.ts
This change is required for compatibility with date-fns v3.
> fix(types): `firstWeekContainsDate` to be only Monday or Thursday

- CONTRIBUTING.md
- src/types/Matchers.ts
Will fix #1977 `CONTRIBUTING.md` file has a bullet point about proofreading the website which points to an old deployment. 
I would like to fix this issue so that the GitHub repository stays consistent and up-to-date. 
Replaced netlify link with [react-day-picker.js.org](https://react-day-picker.js.org/) current website link.
> docs: update Contributing.md

- rollup.config.mjs
When [the new jsx transform was introduced](https://github.com/gpbl/react-day-picker/commit/f3327c92ee2142ec4ced28a257ba3c84386f8127), a copy of the JSX runtime started getting included in the `index.esm.js` bundle. Including this copy meant that we could no longer swap out that module when building our own downstream Preact project. In effect, it broke Preact support.
To fix this, I've updated the `rollup` config to treat `react/jsx-runtime` as an external dependency. By externalizing the JSX runtime in this project, it 1) reduces the library bundle size by 32% and 2) allows downstream projects to use whatever JSX runtime they want.
Could possibly be considered a breaking change, but I don't know the landscape of dependent projects well enough to know if that's true.
Before submitting …
> build: Fix Preact support by externalizing JSX runtime

- types/Props.d.ts
Replaces [deprecated](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30364) `React.SFC` type with `React.FunctionComponent`.
It's required to passing `@types/react` 18 linter check:
```
node_modules/react-day-picker/types/Props.d.ts:47:13 - error TS2694: Namespace 'React' has no exported member 'SFC'.
47     | React.SFC<CaptionElementProps>;
```
Before submitting your pull request, please make sure the following is done:
If this PR addresses any existing issues, please link them here. Example: `Fixes #123`
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
Include screenshots or GIFs if relevant. This is especially important for UI-related changes.
If you have …
> fix(types): replace deprecated React.SFC type

- src/contexts/RootProvider.tsx
Fix for #2072
Before submitting your pull request, please make sure the following is done:
Fixes #2072
I have a project that relies on this repo and I'm currently casting `RootProvider` as `any` to avoid this.  If this does not resolve the issue I am dedicated to a fix because I like to avoid `any` at ALL costs
Candidly, I don't know if this will _definitely_ fix the issue, but it silenced any warning / errors on my local machine in VS Code
> fix(types): Add support for props that exist on downstream providers whose props are derived from prop spreading

- README.md
Fix wrong / outdated link to the react.js project website.
```diff
-https://reactjs.dev/
+https://react.dev/
```
> docs(website): fix wrong link to the react.js project website

- website/docs/using-daypicker/localization.mdx
This simply fixes the url to the locale in date-fns. (see screenshots below)
> docs: fix date-fns locale link in localization.mdx

- examples/TailwindCSS.tsx
- examples/index.ts
- src/UI.ts
- src/helpers/index.ts
- src/index.ts
- website/docs/using-daypicker/styling.mdx
> docs: add Tailwind CSS example

- CHANGELOG.md
Fix the link in the CHANGELOG.md file, which should point to the Selection Modes page in the documentation
> docs: fix link in CHANGELOG.md

- CHANGELOG.md
- examples/ModifiersDisabled.test.tsx
- examples/ModifiersDisabled.tsx
- examples/RangeExcludeDisabled.tsx
- examples/index.ts
- src/selection/useRange.test.tsx
- src/selection/useRange.tsx
- src/types/props.ts
- test/render.tsx
- website/docs/docs/selection-modes.mdx
This PR restore the original behavior of range selection with disabled prop (see https://github.com/gpbl/react-day-picker/issues/1885) and add a new `excludeDisabled` prop that make the new behavior an opt-in.
> feat: add excludeDisabled prop for range mode

- src/style.css
Renamed css variable `end-range_start-color` to `--rdp-range_start-color`. This error is preventing project build.
> fix: typo in css rdp-hidden

- src/style.module.css
Follow up to #2298. I use CSS modules, so my CSS preprocessor (PostCSS) refuses to build in this situation.
> fix: typo in css rdp-hidden module css

- website/docs/upgrading.mdx
Fix broken link: "Upgrading from v7 to v8". The link was missing the `/v8` prefix. Adding it points correctly to the v8 version of the website.
> Fix broken link: "Upgrading from v7 to v8"

- examples/RangeShiftKey.tsx
- src/selection/useRange.test.tsx
- src/selection/useRange.tsx
- src/style.css
- src/style.module.css
- src/utils/addToRange.test.ts
- src/utils/addToRange.ts
> fix: add to range to work with min / required prop

- package.json
> fix(build): add package.json to dist/cjs module

- examples/__snapshots__/Range.test.tsx.snap
- examples/__snapshots__/StylingCssModules.test.tsx.snap
- src/DayPicker.tsx
`data-` attributes, such as `data-selected` or `data-outside`, can help targeting the CSS classes in Tailwind without relying to `aria-` attributes.
E.g.: 
```diff
classNames={{
-   day: "aria-selected:opacity-100"
+   day: "data-selected:opacity-100"
}}
```
> feat: add new data-attributes to the day cells

- website/docs/upgrading.mdx
`fromMonth` has been renamed to `startMonth`,
`toMonth` has been renamed to `endMonth`
Deprecated prop use fixed in upgrade docs
> Replace deprecated props

- examples/SingleRequired.tsx
- src/DayPicker.test.tsx
- src/selection/useMulti.tsx
- src/selection/useRange.tsx
- src/selection/useSingle.tsx
- src/types/props.test.tsx
- src/types/props.ts
- website/docs/docs/selection-modes.mdx
Allow setting `selected={undefined}` even when required is set. Fixes #2334.
Thanks @gharabaghi for your suggestion!
> feat: allow undefined as initially selected value

- src/components/Chevron.tsx
Exporting the type of `Chevron`’s `props` as `ChevronProps`. All other custom components do export their types. It was missing on `Chevron`.
> Export ChevronProps

- website/docs/docs/styling.mdx
Fix `styling.mdx` for a missing variable: `--rdp-range_middle-foreground-color`
> fix: missing variable name

- website/docs/guides/input-fields.mdx
- website/versioned_docs/version-8.10.1/advanced-guides/input-fields.mdx
Fixed some URLs that were incorrect while reading the documentation for input-field.
https://daypicker.dev/guides/input-fields
> Docs: fixed incorrect URLs input-fields.mdx

- src/style.css
- src/style.module.css
Fixes: #2377
Fixed unexpected CSS overwriting on the `button` element
> fix: fix unexpected CSS overwriting on button element 

- src/DayPicker.tsx
Fixes: #2393
This pull request passes the `MonthsDropdown` and `YearsDropdown` classes to the related components. With these classes, users will be able to differentiate between these two dropdowns.
> fix: pass month and years dropdown classes to the related components

- src/types/shared.ts
> fix(types): add formatWeekNumberHeader to Formatters

- examples/TestCase2389.test.tsx
- examples/TestCase2389.tsx
- examples/index.ts
- src/DayPicker.test.tsx
- src/useCalendar.ts
> fix: calendar reset after selection

- src/components/Dropdown.tsx
the `classNames` prop in `DropdownProps` does not contain `UI.MonthsDropdown` and `UI.YearsDropdown`.   These classes are necessary because the user may need them. This pr allows the user to use them.
> fix(types): add missing ClassNames types for dropdowns

- src/components/Nav.tsx
Inside the `NextMonthButton` component, the `disabled` prop is now using the correct _next month_ reference for the `Chevron` component.
> fix: use correct month to disable Chevron of NextMonthButton

- examples/ControlledSelection.test.tsx
- examples/ControlledSelection.tsx
- examples/index.ts
- src/helpers/useControlledValue.ts
- src/selection/useMulti.tsx
- src/selection/useRange.test.tsx
- src/selection/useRange.tsx
- src/selection/useSingle.tsx
> fix: controlled vs. uncontrolled selections

- examples/Input.test.tsx
- examples/ModifiersHidden.test.tsx
- examples/Range.test.tsx
- examples/Weeknumber.test.tsx
- examples/WeeknumberCustom.tsx
- examples/__snapshots__/Range.test.tsx.snap
- examples/__snapshots__/StylingCssModules.test.tsx.snap
- package.json
- pnpm-lock.yaml
- src/DayPicker.test.tsx
- src/DayPicker.tsx
- src/components/WeekNumber.tsx
- test/elements.ts
- test/setup.ts
- add tests to validate HTML
- add missing `type="button"` to Day buttons
- add `scope="col"` to weekdays headers
- add `scope="row"` to week numbers cells
- removed unnecessary `role` attributes.
- note: jest tests must be updated using `cell` instead `gridcell` role
> feat: validate output HTML

- src/helpers/getWeekdays.ts
```
TS2345: Argument of type 'Date' is not assignable to parameter of type 'never'.
23 |   for (let i = 0; i < 7; i++) {
24 |     const day = dateLib.addDays(start, i);
> 25 |     days.push(day);
|               ^^^
26 |   }
27 |   return days;
28 | }
```
When starting a new CRA application, the compiler will throw the above error
- If you are changing code, please add tests to cover the changes.
- Some screenshots or screen recording could help to understand the changes.
- If it is a bug, please provide the code to reproduce it.
Thanks
Add any extra comments or questions here.
> fix(types): argument of type 'Date' is not assignable to parameter of type 'never'

- src/style.css
Fixes a mixup between the CSS variables responsible for the day cells(and button) height & width.
Namely `--rdp-day_button-height` was being set to `var(--rdp-day-width)` and the same for the width.
This made it annoying to have different height and width values through CSS overrides like this since the `day_button` styling would be inverted.
With this small change different height and width values now work without issues.
```
.rdp-root {
--rdp-day-height: 38px;
--rdp-day-width: 46px; 
}
```
The following additional overrides make it work since they are identical to this PR
```
.rdp-root {
--rdp-day-height: 38px;
--rdp-day-width: 46px; 
--rdp-day_button-height: var(
--rdp-day-height
); /* The height …
```
> fix(styles): button height and width are reversed

- website/docs/upgrading.mdx
I noticed that the example code in the documentation at [daypicker.dev/upgrading#7](https://daypicker.dev/upgrading#7-update-your-custom-components) is missing the arrow in the arrow function. I created this pull request to address that issue. I hope this helps improve the documentation!
```typescript
<DayPicker
components={{
-     IconLeft: MyLeftIcon,
+     Chevron: (props) {
+        if (props.orientation === "left") {
+          return <MyLeftIcon {...props} />;
+        }
+       return <Chevron {...props} />;
+     }
}}
/>
```
↓
```typescript
<DayPicker
components={{
-     IconLeft: MyLeftIcon,
+     Chevron: (props) => {
+        if (props.orientation === "left") {
+          return <MyLeftIcon …
```
> Slight modification to sample code

- package.json
Allows consumers to import base CSS using SASS. This gives consumers more flexibility to manipulate the base CSS. For example, forcing the styles under a CSS layer
```scss
@layer third-party-libs {
@import 'pkg:react-day-picker/styles.module';
}
```
OR, forcing the styles to be scoped under a selector
```scss
.my-daypicker {
@import 'pkg:react-day-picker/styles.module';
}
```
- If you are changing code, please add tests to cover the changes.
- Some screenshots or screen recording could help to understand the changes.
- If it is a bug, please provide the code to reproduce it.
Thanks
Add any extra comments or questions here.
> build(style): support importing styles in Sass

- src/selection/useRange.tsx
Improves the performance when selecting days in a range. (part of #2537)
Before: https://github.com/gpbl/react-day-picker/actions/runs/11543002155/artifacts/2109551350
--- 
After: https://github.com/gpbl/react-day-picker/actions/runs/11542948480/artifacts/2109540839
> performance: improve select in `useRange`

- src/DayPicker.tsx
- src/useDayPicker.test.tsx
- src/useDayPicker.ts
- website/docs/guides/custom-components.mdx
Idea from: https://github.com/gpbl/react-day-picker/discussions/2562 by @ImXico
> feat: return `dayPickerProps` from `useDayPicker`

- src/style.css
- src/style.module.css
- website/docs/docs/styling.mdx
The `font` CSS property is not working as expected with CSS variables. I better remove it or the calendar will always be rendered as the system-ui font family.
> fix(style): remove font setting from default style

- src/types/deprecated.ts
- src/types/props.ts
- website/docs/upgrading.mdx
> docs: missing deprecated `initialFocus` and `InternalModifiers` types

- src/formatters/formatMonthDropdown.test.ts
- src/formatters/formatMonthDropdown.ts
- src/helpers/getMonthOptions.ts
Update `formatMonthDropdown` to have the `locale` mandatory argument.
Fixes #2563.
> fix(types): formatMonthDropdown throwing a type error

- examples/__snapshots__/Range.test.tsx.snap
- src/useGetModifiers.test.tsx
- src/useGetModifiers.tsx
Before implementing changes to the `useGetModifiers` function in #2578, I’m adding some tests. 
I could find  a bug where `getModifiers` was returning always an empty `selected` modifier. The selection modifiers are handled separately so they shouldn't appear here.
cc @rodgobbi
> fix: remove selectionStates from useGetModifiers()

- pnpm-lock.yaml
- website/package.json
- website/src/components/ShadowDomWrapper.tsx
- website/src/css/custom.css
Update website to render DayPicker with its original CSS style, by using a Shadow DOM for the examples.
> [!Note]
> Users upgrading to version 9.3 may still require an update to their styles.
Fix #2580.
> docs: use Shadow DOM to display examples 

- examples/StartEndMonthsShowOutsideDays.tsx
- examples/index.ts
- src/useGetModifiers.test.tsx
- src/useGetModifiers.tsx
When using both `showOutsideDays` prop equal to `true` together with a `startMonth` date, the days before the `startMonth` month are not disabled in the calendar and can be clicked and selected.
Screen recording of the issue using the `StartEndMonthsShowOutsideDays` example in this MR, the month March of 2024 is the only enabled, and the 10th day is disabled for showing how a disabled date behaves in the calendar:
https://github.com/user-attachments/assets/cab9d471-02b2-45b2-81f0-514d5d6bdb8f
Days before the `startMonth` month or after the `endMonth` month should be disabled in the calendar.
Screen recording of the fix using the `StartEndMonthsShowOutsideDays` example in this MR:
https://github.com/user-attachments/assets/9487942d-58e7-4ad3-8ded-373ac1d52397
Add logic to flag the days …
> fix: disable outside days outside the before and end month range

- src/style.css
- src/style.module.css
- website/docs/docs/styling.mdx
`rdp-range_middle-foreground-color` is not used anywhere.
> chore(style): remove unused CSS variable

- examples/Dropdown.test.tsx
- examples/DropdownMultipleMonths.test.tsx
- examples/DropdownMultipleMonths.tsx
- src/DayPicker.tsx
- src/helpers/getYearOptions.test.ts
- src/helpers/getYearOptions.ts
- src/types/props.ts
Enable all years available in the year select dropdown. If after selecting the year, the selected month is before the `startMonth` or after the `endMonth`, the day picker selects the closest valid month.
Fix #2549 
https://github.com/user-attachments/assets/d335b0cc-a2f6-4cd5-aff5-6368d8c8b2d5
> Fix: enable all years available in the year select dropdown

- jest.config.ts
- package.json
- pnpm-lock.yaml
Remove ts-jest and configure @swc/jest for JavaScript/TypeScript transformations. This change improves the speed of transforming source files before running tests and supports modern React syntax with automatic runtime.
> refactor(jest): switch to @swc/jest for faster transforms

- examples/Jalali.test.tsx
- examples/Jalali.tsx
- src/jalali.tsx
- website/docs/docs/localization.mdx
> fix(jalali): defaults calendar to `faIR` locale and RTL direction

- src/classes/DateLib.ts
- Improves typedoc compilation time by removing `typeof` from date-fns
- Removes extra documentation from API website
> chore(types): update DateLib to not import types from date-fns

- website/docs/docs/styling.mdx
> docs: fix broken style.css link

- examples/CustomDayButton.tsx
- website/docs/guides/custom-components.mdx
- Fix [Custom Components](https://daypicker.dev/guides/custom-components) docs.
- Update `CustomDayButton` example to reflect documentation changes.
The documentation gives examples of customization based on a [render props](https://react.dev/reference/react/Children#calling-a-render-prop-to-customize-rendering) API, but the customization available is through a component-based API.  
E.g. the `DayButton` component is rendered as [`<components.DayButton {...} />`](https://github.com/gpbl/react-day-picker/blob/main/src/DayPicker.tsx#L535) in the [`DayPicker`](https://github.com/gpbl/react-day-picker/blob/main/src/DayPicker.tsx). To follow a [render props](https://react.dev/reference/react/Children#calling-a-render-prop-to-customize-rendering) API style, it should be manually called in the …
> docs: fix custom components docs

- examples/InvalidMonth.test.tsx
- examples/InvalidMonth.tsx
- examples/index.ts
- src/helpers/getInitialMonth.test.ts
- src/helpers/getInitialMonth.ts
- src/useCalendar.ts
Passing a `month` prop that is outside the `startMonth` and `endMonth` range breaks the calendar.
The PR fixes this edge case by always displaying a valid month as suggested in https://github.com/gpbl/react-day-picker/issues/2671#issuecomment-2613980971.
> fix: display calendar in a valid month when month prop is invalid

- src/types/deprecated.ts
When I was updating from v8 -> v9 I came across the deprecation notice for the `SelectSingleEventHandler`, which gave me the deprecation notice before this PR. When using the suggestion, I was met with:
```
ts: Type '"single"' has no properties in common with type '{ mode?: Mode | undefined; required?: boolean | undefined; }'.
```
Implementing the change I've made on this PR made the warning disappear, though you can also do `SelectHandler<{ required: true }>` and I'm not sure if that's correct. So maybe a type change needs to be made also.
> Fix deprecation suggestion of select event handler types

- examples/DisabledSelectedDate.test.tsx
- examples/DisabledSelectedDate.tsx
- examples/TestCase2047.test.tsx
- examples/index.ts
- src/DayPicker.tsx
Fixes issue https://github.com/gpbl/react-day-picker/issues/2699 by always applying the `selected` modifier if a day is part of the `selected` date.
Notes:
This fix reverts [this change](https://github.com/gpbl/react-day-picker/pull/2171/files#diff-16d85a5debbc177a4de5d5687ff4f6a4d5ed25ad909b77b50d6c22014a551727L75) from a previous fix PR.
What I understood from the context is that the main issue the referred PR fixes is that the disabled days were able to be clicked and selected, so displaying them as `selected` seems correct while ignoring click events coming from them.
Demo:
Tested rendering duplicated `DayPicker`s by rendering them `disabled`.
Added new example for testing the modifier customizations are applied:
> fix: render selected days with selected modifier when disabled

- package.json
This change add the missing typescript types for css imports
> fix: add missing css types to package.json files

- src/DayPicker.tsx
Fixes https://github.com/gpbl/react-day-picker/issues/2715
This PR adds a [visually hidden](https://github.com/reach/reach-ui/blob/main/packages/visually-hidden/src/reach-visually-hidden.tsx) text when the `captionLayout` is of any dropdown type. This text announces to screen readers when the month and year change, following the same pattern for the `CaptionLabel` component used in the default layout (without dropdown).
These changes fix the issue when using the previous or next month buttons.
When using the select dropdown though, the screen reader will announce the new option that gets selected, e.g. July or 2025, and will announce the month and year because the visually hidden text changes.
This in turn causes the screen reader to announce for example "July, July 2025" after selecting …
> fix: add visually hidden text to announce month/year

- src/classes/DateLib.ts
Importing directly to the en-US locale instead of import from "date-fns/locale".
When using react-day-picker and, I found out that the bundle size increased quite a bit. After tweaking import of react-day-picker, look like this single line that import "date-fns/locale" is causing issue. When replace with a direct import to en-US, the bundle size reduced significantly, because only en-US is imported.
Note: normally one would look into https://date-fns.org/v4.1.0/docs/webpack for how to solve bundle size. However this is not necessary if you are not doing dynamic import. In my project we import the exact locale we need, and expect that only those locale will be bundle. However this was broken due to this line in react-day-picker.
> fix: Fix importing of whole locale from date-fns

- website/docs/docs/styling.mdx
I noticed when I was reading through the docs that there were duplicate `--rdp-day-height` definitions in the custom variable docs. 
This change removes the duplicate, very straightforward!
> Removes duplicate '--rdp-day-height' from styling documentation

- package.json
> fix(build): add back `src` to package.json

- src/DayPicker.tsx
- src/useAnimation.test.tsx
- src/useAnimation.ts
This PR fixes `DayPicker` minor bugs caused when trying to navigate months while animating the month transition.
In the same PR, improve tests and refactor `useAnimation` implementation.
Issues:
- Navigation month buttons are not clickable during animation.
- Navigating months during animation causes visual bug in the animation of the next month transition.
The videos below compare the `DayPicker` before and after the fix, running the animation at 25% the default speed.
Before
https://github.com/user-attachments/assets/c2e8c3d4-1626-4d67-ac79-e6676d0d3402
After 
https://github.com/user-attachments/assets/2dd2a25e-11dd-4744-a6cd-dbebdf41df07
> fix(animation): fix issues when navigating months during animation

- website/docs/upgrading.mdx
Update the upgrading guide to include the changes for `selected` as controlled prop. See #2690
> docs: update upgrading guide for controlled prop

- src/helpers/calculateFocusTarget.test.ts
- src/helpers/calculateFocusTarget.ts
Fix #2725
Fix the `calculateFocusTarget` logic.  
Implement a logic that iterates over all days shown in the calendar, and computes the final target day based on the priority of the valid focusable days.
> fix: calculateFocusTarget logic

- src/helpers/getInitialMonth.ts
When month passed as Date type, it would override the provided timezone settings. This fix ensures proper timezone handling.
In `react-day-picker\examples\TimeZone.tsx`, when passing a Date type for the month parameter, the timezone setting was ignored:
Expected:
- First day should be: "Tue Apr 01 2025 00:00:00 GMT+1400 (Line Islands Time)"
- Current day displays correctly
Actual:
- First day shows: "Tue Apr 01 2025 00:00:00 GMT+0800 (台北標準時間)"
- Current day displays incorrectly
After fix:
> fix: prevent timezone override when initialMonth is Date type

- src/DayPicker.tsx
- src/helpers/getInitialMonth.ts
In #2658, we fixed the `initialMonth` prop to account the timezone when using a `Date` object to set the initial month. In this PR, I am applying the same fix to other props that rely on `Date`.
Relevant comment about tests failing due to timezone overrides:
https://github.com/gpbl/react-day-picker/commit/814cb76b584e4be35a64d807ab0de01e99400cdd#commitcomment-155917971
> fix: add timezone to `Date` props

- src/DayPicker.tsx
- src/classes/DateLib.ts
- src/formatters/formatWeekNumber.test.ts
- src/formatters/formatWeekNumber.ts
This PR fixes the week numbers not being properly formatted when using the `numerals` prop:
- Updated `formatWeekNumber` to use `DateLib` and `formatNumber`
- Added more tests
Result:
> fix: format week number with numerals

- examples/Keyboard.test.tsx
- src/DayPicker.tsx
- website/docs/guides/accessibility.mdx
I added a Shift modifier to the keyboard navigation. Specifically,
Shift + ArrowLeft moves the focus to the previous month.
Shift + ArrowRight moves the focus to the next month.
Shift + ArrowUp moves the focus to the previous year.
Shift + ArrowDown moves the focus to the next year.
This feels quite natural and can be useful for those without PageUp/Down buttons on their keyboards.
> feat(accessibility): Shift+Arrows to navigate months/years

- examples/InvalidMonthDefaultLimit.test.tsx
- examples/InvalidMonthDefaultLimit.tsx
- examples/index.ts
- src/DayPicker.tsx
- src/helpers/createGetModifiers.test.ts
- src/helpers/createGetModifiers.ts
- src/helpers/getInitialMonth.test.ts
- src/helpers/getInitialMonth.ts
- src/useCalendar.ts
Fix https://github.com/gpbl/react-day-picker/issues/2776
The issue happens because the valid months of the calendar are calculated internally in the [`useCalendar` hook](https://github.com/gpbl/react-day-picker/blob/main/src/useCalendar.ts#L101) when the `layout` of the day picker is a `dropdown` type, but other inner logic parts of the day picker use the `startMonth` and `endMonth` props as the calendar limits, which in this use case is `undefined`.
This PR unifies the source of truth for the start and end months of the day picker, using the `navStart` and `navEnd` returned by the [`getNavMonths` in the `useCalendar` hook](https://github.com/gpbl/react-day-picker/blob/main/src/useCalendar.ts#L101) as the source of truth.
This also means that from now on, we should **NOT** use the …
> fix: setting defaultMonth the next year when using the dropdown mode does not render the calendar

- src/types/props.ts
To update the customLayout prop value.
> docs: fix captionLayout props doc

- src/types/props.ts
- website/docs/docs/customization.mdx
While reviewing https://github.com/gpbl/react-day-picker/pull/2787 I noticed that the documentation for the `captionLayout` prop could be improved.
This PR makes clearer what the prop does.
> docs: Improve documentation for `captionLayout` prop

- package.json
- pnpm-lock.yaml
We should not lock dependencies, otherwise if client side also depends on those dependencies, multi versions will have been installed
- [*] Bug fix
> build: avoid locking dependencies

- examples/CustomDayButton.test.tsx
- examples/CustomDayButton.tsx
- react-day-picker.code-workspace
- website/docs/guides/custom-components.mdx
This pull request refactors the custom `DayButton` component to use the core `DayButton` from the `react-day-picker` library and updates the documentation to reflect the changes. 
Addresses https://github.com/gpbl/react-day-picker/issues/2806
> docs: update CustomDayButton example and clarify custom components doc

- examples/RangeResetSelection.test.tsx
- examples/RangeResetSelection.tsx
- examples/index.ts
- src/utils/addToRange.test.ts
- src/utils/addToRange.ts
Fixes https://github.com/gpbl/react-day-picker/issues/2813
> fix: select the same day in range mode when range is open and min prop is 0

- src/DayPicker.tsx
- src/helpers/getYearOptions.test.ts
- src/helpers/getYearOptions.ts
- src/types/props.ts
- website/docs/docs/customization.mdx
- website/src/components/Playground/CustomizationFieldset.tsx
A new `reverseYears` prop allows users to reverse the order of years in the dropdown, displaying the current year first. This enhancement improves the usability of the year selection feature.
Fixes #2819
> feat: add `reverseYears` prop
