gpbl/react-day-picker

dist/DayPicker.js
example/src/Example.js
src/DayPicker.js

Allow to pass **className** to the component

Allow className attribute

---

src/DayPicker.js
src/Utils.js
tests/DayPicker.js
tests/Utils.js

Fix behavior when clicking outside days

---

src/DayPicker.js
tests/DayPicker.js

Better behaviour with nav buttons

---

src/DayPicker.js

pass clicked month to onCaptionClick handler instead of the initial one

---

.gitignore
README.md
bower.json
dist/DayPickerGlobal.js
package.json
webpack.config.js

Here's a simple Bower build that'll expose a global `DayPicker` variable. Bower uses git tags to keep track of the current version, so you'll have to add a tag when you change the version in `package.json`.  (Here are the [bower docs](http://bower.io/docs/creating-packages/) for convenience.) Let me know if you have any questions!

Add support for publishing to bower

---

README.md
docs/APIProps.md
docs/DateUtils.md
docs/GettingStarted.md
docs/LocaleUtils.md
docs/LocalizationMoment.md
docs/README.md
docs/Utilities.md
examples/src/examples/InputField.js
examples/src/examples/Localized.js
examples/src/examples/Range.js
examples/src/examples/SelectableDay.js
moment.js
test/DayPicker.js

Update docs and examples to use the new DayPicker exports (see @JKillian's #93)

Update docs for new exports

---

src/DayPicker.js
test/DayPicker.js

Fix bug where endpoint months could not be shown

---

docs/LocaleUtils.md
examples/src/Examples.js
examples/src/examples/YearNavigation.js
examples/src/styles/main.css
src/DayPicker.js
src/LocaleUtils.js
src/addons/MomentLocaleUtils.js
test/DayPicker.js
test/LocaleUtils.js
test/addons/MomentLocaleUtils.js

This pull request adds a `captionElement` prop (#88) and a new `getMonths()` function to `LocaleUtils` that may be useful when using it.

Add captionElement prop

---

bower.json

Let me know if there's anything else needed here! I tested it briefly and seems to work.
Would be great to tag master so that this is available on bower

Allow React 15 dependency in bower.json

---

DayPicker.js
docs/APIProps.md
src/DayPicker.js
src/Navbar.js
test/DayPicker.js
test/Navbar.js

Implemented navbarComponent property

navbarComponent property

---

src/Day.js
src/DayPicker.js

I've added the prop onDayFocus

Added onDayFocus prop

---

docs/DateUtils.md
src/DateUtils.js
test/DateUtils.js

While using the picker, I felt the need to exclude days in the future, instead of days in the past. There is nothing ground-breaking here.
I've also added tests and documentation.

Add isFutureDay DateUtils function

---

examples/src/Examples.js
examples/src/examples/CalendarOverlay.js
examples/src/examples/InputFieldOverlay.js
examples/webpack.config.js

Updates @frandsaw 's code merged from his [pull request](https://github.com/gpbl/react-day-picker/pull/211) to handle input's change events.

InputField + Overlay example (close #98)

---

src/addons/MomentLocaleUtils.js
test/addons/MomentLocaleUtils.js

moment utilities: make sure weekdays names begin from Sunday

---

src/Helpers.js

Do not use isInteger

---

docs/API.md
docs/APIProps.md
examples/src/examples/YearNavigation.js
src/DayPicker.js
test/daypicker/rendering.js

Add new month prop

---

README.md

fix constructor spelling

---

examples/src/examples/RangeAdvanced.js

I tried using the RangeAdvanced example and realized that when the first day is selected and then an older date is clicked another day selection is need for it to get to a valid state and show to mouse enter "effects" correctly.
I changed it a little bit to fix it and the final result imho is a little more easy to understand, so I would like to share it with everybody.
I tried to keep it the same but, if it is of yours interest I have a version with an onRangeSelected prop.

Fix RangeAdvanced example

---

examples/src/examples/AdvancedModifiers.js

Seems like it should be "first" instead of "blahblah", based on the modifier functions.

Fixed advanced modifiers example

---

DayPicker.js

I noticed that ModifiersUtils is not exported from the main file. I think I forgot to add that into my last PR.

ModifiersUtils export from DayPicker.js

---

docs/DateUtils.md
docs/DayPickerAPI.md
examples/src/Examples.js
examples/src/examples/WeekNumbers.js
examples/webpack.config.js
src/DateUtils.js
src/DayPicker.js
src/Month.js
src/Weekdays.js
src/classNames.js
src/style.css
test/daypicker/events.js
test/daypicker/rendering.js
types/index.d.ts

Add showWeeksNumber, onWeekClick props

---

.eslintrc
package.json
yarn.lock

chore(package): update eslint-config-airbnb to version 15.0.1

---

examples/src/examples/InputField.js
src/DayPickerInput.js
test/daypickerinput/events.js
test/daypickerinput/rendering.js

Update Input state when receiving new value from props

---

DayPicker.dist.js
README.md
docs/Examples.md
docs/SUMMARY.md
webpack.config.js

Include DayPickerInput in dist files

---

.eslintrc
src/Caption.js
src/DayPicker.js
src/Navbar.js
test/daypicker/events.js
test/daypicker/navigation.js
test/daypicker/rendering.js

Re-enable jsx-a11y rules

---

src/Caption.js
src/Day.js
src/DayPicker.js
src/Helpers.js
src/Month.js
src/Navbar.js
src/Weekday.js
src/Weekdays.js
test/DateUtils.js
test/daypicker/events.js
test/daypicker/navigation.js
test/daypicker/rendering.js
yarn.lock

Improve re rendering time

---

src/Day.js

Remove role="gridcell" from non interactive day

---

src/style.css
test/Navbar.js

Fix test for nav button with interaction disabled

---

docs/DayPickerAPI.md
src/DayPicker.js
src/classNames.js
src/style.css
test/daypicker/events.js
test/daypicker/navigation.js
test/daypicker/rendering.js
types/index.d.ts

Fix interactive elements

---

docs/_includes/home.html

Looks like styles import is missing `.css`

Fix css import in example

---

src/DayPickerInput.js
test/daypickerinput/events.js

Call onDayChange if the input's value is empty

---

src/DayPickerInput.js
test/daypickerinput/rendering.js

Update when `dayPickerProps.month` is updated

---

src/DayPicker.js
src/DayPickerInput.js
src/Navbar.js
src/keys.js
test/Navbar.js
test/daypicker/events.js
test/daypicker/navigation.js
test/daypickerinput/events.js

Make Next/Previous button working with keyboard

---

docs/examples/src/modifiers-styles.js

Just a simple typo. Thanks for the great and highly customizable library!

Fix day of week typo

---

docs/docs/api-input.md
package.json
src/DayPickerInput.js
test/daypicker/rendering.js
test/daypickerinput/rendering.js
yarn.lock

Accept multiple formats

---

docs/docs/index.md

💭 Please explain clearly your changes...
💬 If they involve a lot of code, discuss them first on our gitter room: 

Fix yarn install command on index.md

---

docs/docs/basics.md

💭 Please explain clearly your changes...
💬 If they involve a lot of code, discuss them first on our gitter room: 

Fix react api example

---

docs/docs/index.md

💭 Please explain clearly your changes...
💬 If they involve a lot of code, discuss them first on our gitter room: 

Fix css import example

---

src/DayPickerInput.js
test/daypicker/events.js

Input moment locale utils

---

src/DayPickerInput.js
test/daypickerinput/rendering.js

Do not override numberOfMonths

---

CHANGELOG.md
docs/package.json
docs/src/code-samples/examples/customization-today-button.js
docs/src/pages/api/DayPicker.js
docs/yarn.lock
src/DayPicker.js
test/daypicker/events.js

Add onTodayButtonClick prop

---

src/DayPicker.js
test/daypicker/rendering.js

Remove role=“application”

---

src/style.css

PR for #557. It removes dotted underline from weekdays.

Removes underline from weekdays

---

src/DayPickerInput.js

Update value when changed from props

---

CHANGELOG.md
docs/src/pages/api/DayPickerInput.js
src/DayPickerInput.js
src/Month.js
test/daypickerinput/events.js

Add `inputProps` prop

---

src/DayPicker.js
test/daypicker/navigation.js

Fix updated month prop not updating calendar

---

src/DayPickerInput.js
src/keys.js
test/daypickerinput/events.js

Intercept TAB key to fix body being focused

---

package.json
src/Day.js

Remove object-assign package in favor of spread operator

---

package.json
yarn.lock

This is better if somebody will contribute from windows

Add cross-env for save environment variables

---

src/Month.js

Do not show outside days when fromMonth/toMonth

---

DayPicker.dist.js
DayPicker.js
src/DayPicker.js
src/index.js
webpack.config.js

Reverts gpbl/react-day-picker#637

Revert "Replace env with production to fix umd crashing in runtime"

---

src/Month.js

Revert "Do not show outside days when fromMonth/toMonth"

---

DayPicker.dist.js
DayPicker.js
src/DayPicker.js
src/index.js
webpack.config.js

Reverts gpbl/react-day-picker#651

Revert "Fix umd build"

---

DayPicker.dist.js
DayPicker.js
src/DayPicker.js
src/index.js
webpack.config.js

Reverts gpbl/react-day-picker#656

Revert "Revert "Fix umd build""

---

DayPicker.js
src/DayPicker.js

Make sure utilities are exported again

---

src/Month.js
test/daypicker/events.js
test/daypicker/rendering.js

Use last day of the week to get the week number

---

src/DayPickerInput.js

Reset the current displayed month when showing the overlay

---

package.json
src/DayPicker.js
src/DayPickerInput.js
yarn.lock

Add support for react 17

---

src/DayPickerInput.js
test/daypickerinput/events.js

Do not show overlay if input is disabled

---

src/DayPickerInput.js
src/Helpers.js
test/daypickerinput/rendering.js

Fix IE issue

---

docs/src/code-samples/examples/input-from-to.js

Closes https://github.com/gpbl/react-day-picker/issues/735.
Please let me know if there are other steps necessary to get this merged in.

Remove leftover focus in docs (closes #735)

---

src/DayPicker.js

The previous PR, for the disabled check, only fixed the DayPickerInput. This also fixed the normal DayPicker.

Added disabled check to handleDayClick in DayPicker.

---

src/DayPickerInput.js

Simplified modifier reducer in DayPickerInput.js

Simplify modifier reduce function

---

src/Navbar.js

eslint was giving this issue:
```
8:3  error  defaultProps should be placed after propTypes  react/sort-comp
```
This pr should fix that

Fix navbar eslint issue

---

docs/src/pages/api/DayPicker.js
docs/src/pages/contributing.js
docs/src/pages/index.js
docs/src/pages/support.js
docs/src/ui/Footer.js
docs/src/ui/GitHubButton.js
docs/src/ui/Header.js

Just fixing a pet peeve of mine

GitHub has a capital H

---

docs/src/pages/examples/modifiers.js

Hmm... I read this:
>* 🙏🏽 Please **DO NOT** build files or update the docs in your pull request – as this may cause git conflicts. Thanks!
How else should I propose a typo fix for the docs? I'll add this here and wait to hear from you :)

fix typo in 'monday'

---

docs/src/code-samples/examples/input-state.js
docs/src/pages/api/DayPickerInput.js
src/DayPickerInput.js
test/daypickerinput/events.js
types/props.d.ts

Pass dayPickerInput instance to onDayChange

---

src/DayPicker.js

action taken from this issue https://github.com/gpbl/react-day-picker/issues/789 😉

Revert disabled check for handleDayClick

---

docs/src/pages/docs/getting-started.js

Fixes a small typo in the docs.

Fixes Typo

---

docs/src/pages/api/DayPicker.js

API doc typo fix

---

moment.d.ts
package.json
types/moment.d.ts

Adding TypeScript declaration for moment locale utils

---

docs/src/pages/api/DayPickerInput.js

The small fix: unnecessary bracket in the example

The small fix: unnecessary bracket in the example

---

docs/src/code-samples/examples/input-date-fns.js
docs/src/pages/examples/input-date-fns.js

support date-fns v2 in example

---

types/props.d.ts

Hello!
I took this small bug from #966

Add style type to DayPickerInputProps (fix #966)

---

types/props.d.ts
types/utils.d.ts

Fixes issues 2 and 3 raised in https://github.com/gpbl/react-day-picker/issues/1009

Fix TypeScript types ruined in v7.4.1

---

DayPicker/index.js
DayPicker/package.json
package.json

Add DayPicker dir export

---

docs/src/code-samples/examples/selected-multiple.js

Update selected multiple example

---

package.json

This pull requests adds React 17 as peer dependency

Add react 17 as peer dependency

---

packages/react-day-picker/README.md

docs: fix typo

---

packages/react-day-picker/src/contexts/DayPicker/defaultClassNames.ts
packages/react-day-picker/style.css
packages/react-day-picker/style.css.d.ts

This is a regression from #1315.

fix: rename caption_first to caption_start

---

packages/react-day-picker/src/components/Table/Table.tsx
packages/react-day-picker/test/po/index.ts

E.g.: https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html

chore: move Table to grid role

---

packages/react-day-picker/src/components/Footer/Footer.test.tsx
packages/react-day-picker/test/po/PageObjects.ts
packages/react-day-picker/test/po/po.ts

changing any instance of `getByRole('table')` to `getByRole('grid')`...

fix tests?

---

.github/workflows/publish.yml

Changes to the package.json scripts broke this.
This gets it working again (probably). I ran each step individually, except the last one.

Fix the publish workflow

---

website/examples/numbering-system.tsx
website/test-integration/examples/numbering-system.test.tsx
yarn.lock

https://github.com/gpbl/react-day-picker/runs/4576850566?check_suite_focus=true

Fixing numbering system tests

---

website/examples/date-picker-dialog.tsx
website/test-integration/examples/date-picker-dialog.test.tsx

I forgot to do this for my previous work.
Not sure about plumbing today through to the example...it makes the example slightly more complex...but I think it's ok

chore: add tests for date-picker-dialog website example

---

docs/src/pages/api/DayPickerInput.js

Fixed a typo in the docs api page DayPickerInput

Fixed a typo in the docs api page DayPickerInput

---

packages/react-day-picker/src/components/Navigation/Navigation.test.tsx
packages/react-day-picker/src/components/Navigation/Navigation.tsx
packages/react-day-picker/src/hooks/useDayRender/useDayRender.test.tsx
packages/react-day-picker/src/hooks/useDayRender/useDayRender.tsx
packages/react-day-picker/src/style.css
packages/react-day-picker/test/po.ts
website/test-integration/examples/from-to-month.test.tsx
website/test-integration/examples/from-to-year.test.tsx
website/test-integration/examples/modifiers-disabled.test.tsx

Use aria-disabled instead of disabled

---

packages/react-day-picker/src/components/Navigation/Navigation.test.tsx
packages/react-day-picker/src/components/Navigation/Navigation.tsx
packages/react-day-picker/src/hooks/useDayRender/useDayRender.test.tsx
packages/react-day-picker/src/hooks/useDayRender/useDayRender.tsx
packages/react-day-picker/src/style.css
packages/react-day-picker/test/po.ts
website/test-integration/examples/from-to-month.test.tsx
website/test-integration/examples/from-to-year.test.tsx
website/test-integration/examples/modifiers-disabled.test.tsx

Reverts gpbl/react-day-picker#1451

Revert "Use aria-disabled instead of disabled"

---

packages/react-day-picker/package.json
packages/react-day-picker/src/style.css

fix for: https://github.com/gpbl/react-day-picker/issues/1472

Use pure selector for root variables

---

packages/react-day-picker/src/style.css

Reverts gpbl/react-day-picker#1481

Revert "Use pure selector for root variables"

---

correct.sh
packages/react-day-picker/src/contexts/DayPicker/DayPickerContext.tsx
packages/react-day-picker/src/contexts/DayPicker/useDayPicker.ts
packages/react-day-picker/src/contexts/Focus/FocusContext.tsx
packages/react-day-picker/src/contexts/Focus/useFocusContext.ts
packages/react-day-picker/src/contexts/Modifiers/useModifiers.ts
packages/react-day-picker/src/contexts/Navigation/NavigationContext.tsx
packages/react-day-picker/src/contexts/Navigation/useNavigation.ts
packages/react-day-picker/src/contexts/SelectMultiple/useSelectMultiple.ts
packages/react-day-picker/src/contexts/SelectRange/useSelectRange.ts
packages/react-day-picker/src/contexts/SelectSingle/useSelectSingle.ts
packages/react-day-picker/src/hooks/useActiveModifiers/useActiveModifiers.tsx
packages/react-day-picker/src/hooks/useDayRender/useDayRender.tsx
packages/react-day-picker/src/hooks/useSelectedDays/useSelectedDays.ts
packages/react-day-picker/src/style.css
packages/react-day-picker/src/types/DayPickerBase.ts
packages/react-day-picker/src/types/Modifiers.ts
website/docs/basics/keyboard.md
website/docs/guides/custom-components.md
website/examples/custom-caption.tsx
website/examples/custom-components.tsx
website/examples/custom-day.tsx
website/examples/range-shift-key.tsx

Improve docs for custom components. Related: #1486.

website: update custom components docs

---

packages/react-day-picker/src/components/Day/Day.test.tsx
packages/react-day-picker/src/components/Day/Day.tsx
packages/react-day-picker/src/components/Dropdown/Dropdown.test.tsx
packages/react-day-picker/src/components/Dropdown/Dropdown.tsx
packages/react-day-picker/src/components/MonthsDropdown/MonthsDropdown.test.tsx
packages/react-day-picker/src/components/MonthsDropdown/MonthsDropdown.tsx
packages/react-day-picker/src/components/MonthsDropdown/__snapshots__/MonthsDropdown.test.tsx.snap
packages/react-day-picker/src/components/Navigation/Navigation.test.tsx
packages/react-day-picker/src/components/Navigation/Navigation.tsx
packages/react-day-picker/src/components/WeekNumber/WeekNumber.test.tsx
packages/react-day-picker/src/components/WeekNumber/WeekNumber.tsx
packages/react-day-picker/src/components/WeekNumber/__snapshots__/WeekNumber.test.tsx.snap
packages/react-day-picker/src/components/YearsDropdown/YearsDropdown.test.tsx
packages/react-day-picker/src/components/YearsDropdown/YearsDropdown.tsx
packages/react-day-picker/src/components/YearsDropdown/__snapshots__/YearsDropdown.test.tsx.snap
packages/react-day-picker/src/style.css

changed: focus vs focus-visible styles

---

packages/react-day-picker/src/types/EventHandlers.ts

chore: updated SelectSingleEventHandler interface to type

---

packages/react-day-picker/src/components/Month/Month.test.tsx
packages/react-day-picker/src/components/Month/Month.tsx
packages/react-day-picker/src/contexts/DayPicker/DayPickerContext.tsx
packages/react-day-picker/src/contexts/DayPicker/useDayPicker.test.ts
packages/react-day-picker/src/types/DayPickerBase.ts

feat: add new id prop

---

packages/react-day-picker/src/contexts/Modifiers/utils/isMatch.test.ts
packages/react-day-picker/src/contexts/Modifiers/utils/isMatch.ts
packages/react-day-picker/src/types/Matchers.ts

fix: isMatch to match open DateIntervals

---

packages/react-day-picker/rollup.config.js

build: fix CSS module types 

---

packages/react-day-picker/src/contexts/Modifiers/utils/isDateInRange.test.ts
packages/react-day-picker/src/contexts/Modifiers/utils/isDateInRange.ts
packages/react-day-picker/src/contexts/SelectRange/SelectRangeContext.test.ts
packages/react-day-picker/src/contexts/SelectRange/SelectRangeContext.tsx
website/test-integration/examples/__snapshots__/range.test.tsx.snap
website/test-integration/examples/range.test.tsx

fix: range_middle class is added to days not in the selected range

---

packages/react-day-picker/src/components/Button/Button.tsx

chore: improve ButtonProps type

---

packages/react-day-picker/src/components/Footer/Footer.tsx
packages/react-day-picker/src/components/Table/Table.test.tsx
packages/react-day-picker/src/components/Table/Table.tsx
packages/react-day-picker/src/components/Table/__snapshots__/Table.test.tsx.snap
packages/react-day-picker/src/types/DayPickerBase.ts

feat: add displayMonth prop to Footer

---

packages/react-day-picker/src/components/CaptionNavigation/CaptionNavigation.tsx
website/test-integration/examples/rtl.test.tsx

fix: caption buttons inverted when using RTL and multiple months

---

packages/react-day-picker/src/components/Root/Root.test.tsx
packages/react-day-picker/src/components/Root/Root.tsx
packages/react-day-picker/src/hooks/useDayEventHandlers/useDayEventHandlers.test.tsx
packages/react-day-picker/src/types/DayPickerBase.ts
website/examples/container-attributes.tsx
website/test-integration/examples/__snapshots__/range.test.tsx.snap
website/test-integration/examples/container-attributes.test.tsx

feat: add id, data- and aria- attributes to the root element

---

packages/react-day-picker/src/DayPicker.tsx
packages/react-day-picker/src/components/Root/Root.test.tsx
packages/react-day-picker/src/components/Root/Root.tsx
packages/react-day-picker/src/types/DayPickerBase.ts
website/examples/container-attributes.tsx
website/test-integration/examples/container-attributes.test.tsx

fix: cannot extend DayPickerProps, DataAttributes interface

---

src/components/Caption/Caption.tsx
src/components/CaptionDropdowns/CaptionDropdowns.tsx
src/components/CaptionLabel/CaptionLabel.tsx
src/components/Month/Month.tsx
website/examples/dropdown-multiple-months.tsx
website/test-integration/examples/dropdown-multiple-months.test.tsx

fix: dropdown may navigate to the wrong month when multiple months are set

---

.eslintrc.cjs
package.json
pnpm-lock.yaml
src/.eslintrc.cjs
src/contexts/providers.tsx
src/contexts/useModifiers.tsx
src/contexts/useProps.tsx
src/types/props.ts
src/types/shared.ts
src/utils/typeguards.ts
website/.eslintrc.cjs
website/examples-v8/react-day-picker-v8.tsx

build: add eslint settings for required extensions

---

website/versioned_docs/version-8.10.1/using-daypicker/styling.mdx

i noticed the path for importing the `style.module.css` was incorrect `react-day-picker/style.module.css`, as the style module is actually in the `react-day-picker/dist` directory so i made the correction.
Before submitting your pull request, please make sure the following is done:
If this PR addresses any existing issues, please link them here. Example: `Fixes #123`
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
Include screenshots or GIFs if relevant. This is especially important for UI-related changes.
If you have any additional comments or questions, please add them here.

docs: updated styling.mdx

---

website/docs/using-daypicker/selection-modes.mdx

Wrong example on the documentation

docs: update selection-modes.mdx

---

website/docs/upgrading.mdx

A diff in the migration guide probably has a typo.

[Doc] Update upgrading.mdx for typo

---

src/useCalendar.ts

fix: update the displayed month only if start/end month change

---

src/utils/dateMatchModifiers.ts

fix(utilities): dateMatchModifiers to use defaultDateLib

---

website/docs/upgrading.mdx

PR #2211 renamed `types-deprecated.ts` to be `types/deprecated.ts`. This PR adjusts sources to changes.
- If you are changing code, please add tests to cover the changes.
- Some screenshots or screen recording could help to understand the changes.
- If it is a bug, please provide the code to reproduce it.
Thanks
Add any extra comments or questions here.

docs: update types/deprecated.ts reference

---

src/components/Dropdown.tsx

feat(types): remove restrictions to components, classNames prop types

---

examples/Jalali.tsx
package.json
pnpm-lock.yaml
src/jalali.tsx

build(deps): update to date-fns@4

---

package.json

- Added `tsconfig-base.json` to `files` in `package.json`.
Should solve #2491

build: add tsconfig-base.json

---

examples/TestCase2585.test.tsx
examples/TestCase2585.tsx
examples/index.ts
src/helpers/getDates.test.ts
src/helpers/getDates.ts
src/helpers/getMonths.ts

fix: months with 4 weeks not displaying 6 weeks w/ fixedWeeks

---

src/style.css
src/style.module.css

https://css-tricks.com/copy-the-browsers-native-focus-styles/

fix(styles): dropdown not appearing as focused

---

website/docs/docs/styling.mdx

Fixes link to `style.css`.
- If you are changing code, please add tests to cover the changes.
- Some screenshots or screen recording could help to understand the changes.
- If it is a bug, please provide the code to reproduce it.
Thanks
Add any extra comments or questions here.

docs: update styling.mdx

---

website/docs/guides/input-fields.mdx

Missing `}` in the example.
Thanks
Great stuff!

Missing `}` in input-fields.mdx

---

src/helpers/getMonthOptions.test.ts
src/helpers/getMonthOptions.ts

Fixes issue in https://github.com/gpbl/react-day-picker/pull/2614#issuecomment-2525325472

fix: display all months in dropdown

---

website/src/css/custom.css
website/src/pages/playground.tsx

website: improve accessibility

---

package.json

build: remove extra files from package.json

---

package.json

Regression from https://github.com/gpbl/react-day-picker/pull/2692.

build: add missing .css entries in package.json files

---

src/components/Day.tsx

Fix docs based on https://github.com/gpbl/react-day-picker/discussions/2706

docs: fix Day components documentation

---

examples/PersianEn.test.tsx
examples/PersianEn.tsx
src/classes/DateLib.ts

I'm adding a failing test to reproduce #2704. 
Looks like a regression from https://github.com/gpbl/react-day-picker/pull/2655.

(fix) Persian calendar with enUS locale displaying empty week

---

examples/Input.tsx

Fixes #2724 causing search appearing when typing `/`.

docs: prevent propagation on input keydown

---

src/types/props.ts
website/docs/docs/selection-modes.mdx

Follow-up from https://github.com/gpbl/react-day-picker/discussions/2752 to improve docs about disabling dates in DayPicker.

docs: add more docs about for disabled prop
